// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wippy/registry/identity/v1/organization_membership.proto

package identityv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a user's membership in an organization.
type OrganizationMembership struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the membership.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The id of the organization.
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// The id of the user.
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The role of the user in the organization.
	Role OrganizationRole `protobuf:"varint,4,opt,name=role,proto3,enum=wippy.registry.identity.v1.OrganizationRole" json:"role,omitempty"`
	// The time the membership was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last time the membership was updated.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMembership) Reset() {
	*x = OrganizationMembership{}
	mi := &file_wippy_registry_identity_v1_organization_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMembership) ProtoMessage() {}

func (x *OrganizationMembership) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_identity_v1_organization_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMembership.ProtoReflect.Descriptor instead.
func (*OrganizationMembership) Descriptor() ([]byte, []int) {
	return file_wippy_registry_identity_v1_organization_membership_proto_rawDescGZIP(), []int{0}
}

func (x *OrganizationMembership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationMembership) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *OrganizationMembership) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrganizationMembership) GetRole() OrganizationRole {
	if x != nil {
		return x.Role
	}
	return OrganizationRole_ORGANIZATION_ROLE_UNSPECIFIED
}

func (x *OrganizationMembership) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *OrganizationMembership) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

var File_wippy_registry_identity_v1_organization_membership_proto protoreflect.FileDescriptor

const file_wippy_registry_identity_v1_organization_membership_proto_rawDesc = "" +
	"\n" +
	"8wippy/registry/identity/v1/organization_membership.proto\x12\x1awippy.registry.identity.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a2wippy/registry/identity/v1/organization_role.proto\"\xe5\x02\n" +
	"\x16OrganizationMembership\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\x124\n" +
	"\x0forganization_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0eorganizationId\x12$\n" +
	"\auser_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06userId\x12H\n" +
	"\x04role\x18\x04 \x01(\x0e2,.wippy.registry.identity.v1.OrganizationRoleB\x06\xbaH\x03\xc8\x01\x01R\x04role\x12C\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"createTime\x12C\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"updateTimeBMZKgithub.com/wippyai/module-registry-proto-go/registry/identity/v1;identityv1b\x06proto3"

var (
	file_wippy_registry_identity_v1_organization_membership_proto_rawDescOnce sync.Once
	file_wippy_registry_identity_v1_organization_membership_proto_rawDescData []byte
)

func file_wippy_registry_identity_v1_organization_membership_proto_rawDescGZIP() []byte {
	file_wippy_registry_identity_v1_organization_membership_proto_rawDescOnce.Do(func() {
		file_wippy_registry_identity_v1_organization_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_organization_membership_proto_rawDesc), len(file_wippy_registry_identity_v1_organization_membership_proto_rawDesc)))
	})
	return file_wippy_registry_identity_v1_organization_membership_proto_rawDescData
}

var file_wippy_registry_identity_v1_organization_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wippy_registry_identity_v1_organization_membership_proto_goTypes = []any{
	(*OrganizationMembership)(nil), // 0: wippy.registry.identity.v1.OrganizationMembership
	(OrganizationRole)(0),          // 1: wippy.registry.identity.v1.OrganizationRole
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
}
var file_wippy_registry_identity_v1_organization_membership_proto_depIdxs = []int32{
	1, // 0: wippy.registry.identity.v1.OrganizationMembership.role:type_name -> wippy.registry.identity.v1.OrganizationRole
	2, // 1: wippy.registry.identity.v1.OrganizationMembership.create_time:type_name -> google.protobuf.Timestamp
	2, // 2: wippy.registry.identity.v1.OrganizationMembership.update_time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wippy_registry_identity_v1_organization_membership_proto_init() }
func file_wippy_registry_identity_v1_organization_membership_proto_init() {
	if File_wippy_registry_identity_v1_organization_membership_proto != nil {
		return
	}
	file_wippy_registry_identity_v1_organization_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_organization_membership_proto_rawDesc), len(file_wippy_registry_identity_v1_organization_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wippy_registry_identity_v1_organization_membership_proto_goTypes,
		DependencyIndexes: file_wippy_registry_identity_v1_organization_membership_proto_depIdxs,
		MessageInfos:      file_wippy_registry_identity_v1_organization_membership_proto_msgTypes,
	}.Build()
	File_wippy_registry_identity_v1_organization_membership_proto = out.File
	file_wippy_registry_identity_v1_organization_membership_proto_goTypes = nil
	file_wippy_registry_identity_v1_organization_membership_proto_depIdxs = nil
}
