// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wippy/registry/identity/v1/organization_service.proto

package identityv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrganizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization name
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_wippy_registry_identity_v1_organization_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_identity_v1_organization_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_wippy_registry_identity_v1_organization_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationResponse) Reset() {
	*x = CreateOrganizationResponse{}
	mi := &file_wippy_registry_identity_v1_organization_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResponse) ProtoMessage() {}

func (x *CreateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_identity_v1_organization_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_wippy_registry_identity_v1_organization_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganizationResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type ListOrganizationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by specific organization references (id or name). Return all if empty.
	Refs          []*OrganizationRef `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsRequest) Reset() {
	*x = ListOrganizationsRequest{}
	mi := &file_wippy_registry_identity_v1_organization_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsRequest) ProtoMessage() {}

func (x *ListOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_identity_v1_organization_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_wippy_registry_identity_v1_organization_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListOrganizationsRequest) GetRefs() []*OrganizationRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

type ListOrganizationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The listed Organizations.
	Organizations []*Organization `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_wippy_registry_identity_v1_organization_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_identity_v1_organization_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_wippy_registry_identity_v1_organization_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

var File_wippy_registry_identity_v1_organization_service_proto protoreflect.FileDescriptor

const file_wippy_registry_identity_v1_organization_service_proto_rawDesc = "" +
	"\n" +
	"5wippy/registry/identity/v1/organization_service.proto\x12\x1awippy.registry.identity.v1\x1a\x1bbuf/validate/validate.proto\x1a-wippy/registry/identity/v1/organization.proto\"X\n" +
	"\x19CreateOrganizationRequest\x12;\n" +
	"\x04name\x18\x01 \x01(\tB'\xbaH$\xc8\x01\x01r\x1f\x10\x02\x18 2\x19^[a-z][a-z0-9-]*[a-z0-9]$R\x04name\"j\n" +
	"\x1aCreateOrganizationResponse\x12L\n" +
	"\forganization\x18\x01 \x01(\v2(.wippy.registry.identity.v1.OrganizationR\forganization\"[\n" +
	"\x18ListOrganizationsRequest\x12?\n" +
	"\x04refs\x18\x01 \x03(\v2+.wippy.registry.identity.v1.OrganizationRefR\x04refs\"k\n" +
	"\x19ListOrganizationsResponse\x12N\n" +
	"\rorganizations\x18\x01 \x03(\v2(.wippy.registry.identity.v1.OrganizationR\rorganizations2\xa8\x02\n" +
	"\x13OrganizationService\x12\x88\x01\n" +
	"\x12CreateOrganization\x125.wippy.registry.identity.v1.CreateOrganizationRequest\x1a6.wippy.registry.identity.v1.CreateOrganizationResponse\"\x03\x90\x02\x02\x12\x85\x01\n" +
	"\x11ListOrganizations\x124.wippy.registry.identity.v1.ListOrganizationsRequest\x1a5.wippy.registry.identity.v1.ListOrganizationsResponse\"\x03\x90\x02\x01BMZKgithub.com/wippyai/module-registry-proto-go/registry/identity/v1;identityv1b\x06proto3"

var (
	file_wippy_registry_identity_v1_organization_service_proto_rawDescOnce sync.Once
	file_wippy_registry_identity_v1_organization_service_proto_rawDescData []byte
)

func file_wippy_registry_identity_v1_organization_service_proto_rawDescGZIP() []byte {
	file_wippy_registry_identity_v1_organization_service_proto_rawDescOnce.Do(func() {
		file_wippy_registry_identity_v1_organization_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_organization_service_proto_rawDesc), len(file_wippy_registry_identity_v1_organization_service_proto_rawDesc)))
	})
	return file_wippy_registry_identity_v1_organization_service_proto_rawDescData
}

var file_wippy_registry_identity_v1_organization_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wippy_registry_identity_v1_organization_service_proto_goTypes = []any{
	(*CreateOrganizationRequest)(nil),  // 0: wippy.registry.identity.v1.CreateOrganizationRequest
	(*CreateOrganizationResponse)(nil), // 1: wippy.registry.identity.v1.CreateOrganizationResponse
	(*ListOrganizationsRequest)(nil),   // 2: wippy.registry.identity.v1.ListOrganizationsRequest
	(*ListOrganizationsResponse)(nil),  // 3: wippy.registry.identity.v1.ListOrganizationsResponse
	(*Organization)(nil),               // 4: wippy.registry.identity.v1.Organization
	(*OrganizationRef)(nil),            // 5: wippy.registry.identity.v1.OrganizationRef
}
var file_wippy_registry_identity_v1_organization_service_proto_depIdxs = []int32{
	4, // 0: wippy.registry.identity.v1.CreateOrganizationResponse.organization:type_name -> wippy.registry.identity.v1.Organization
	5, // 1: wippy.registry.identity.v1.ListOrganizationsRequest.refs:type_name -> wippy.registry.identity.v1.OrganizationRef
	4, // 2: wippy.registry.identity.v1.ListOrganizationsResponse.organizations:type_name -> wippy.registry.identity.v1.Organization
	0, // 3: wippy.registry.identity.v1.OrganizationService.CreateOrganization:input_type -> wippy.registry.identity.v1.CreateOrganizationRequest
	2, // 4: wippy.registry.identity.v1.OrganizationService.ListOrganizations:input_type -> wippy.registry.identity.v1.ListOrganizationsRequest
	1, // 5: wippy.registry.identity.v1.OrganizationService.CreateOrganization:output_type -> wippy.registry.identity.v1.CreateOrganizationResponse
	3, // 6: wippy.registry.identity.v1.OrganizationService.ListOrganizations:output_type -> wippy.registry.identity.v1.ListOrganizationsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wippy_registry_identity_v1_organization_service_proto_init() }
func file_wippy_registry_identity_v1_organization_service_proto_init() {
	if File_wippy_registry_identity_v1_organization_service_proto != nil {
		return
	}
	file_wippy_registry_identity_v1_organization_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_organization_service_proto_rawDesc), len(file_wippy_registry_identity_v1_organization_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_registry_identity_v1_organization_service_proto_goTypes,
		DependencyIndexes: file_wippy_registry_identity_v1_organization_service_proto_depIdxs,
		MessageInfos:      file_wippy_registry_identity_v1_organization_service_proto_msgTypes,
	}.Build()
	File_wippy_registry_identity_v1_organization_service_proto = out.File
	file_wippy_registry_identity_v1_organization_service_proto_goTypes = nil
	file_wippy_registry_identity_v1_organization_service_proto_depIdxs = nil
}
