// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wippy/registry/identity/v1/organization_membership_service.proto

package identityv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddOrganizationMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the organization.
	OrganizationId string `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// The id of the user.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrganizationMemberRequest) Reset() {
	*x = AddOrganizationMemberRequest{}
	mi := &file_wippy_registry_identity_v1_organization_membership_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrganizationMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrganizationMemberRequest) ProtoMessage() {}

func (x *AddOrganizationMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_identity_v1_organization_membership_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrganizationMemberRequest.ProtoReflect.Descriptor instead.
func (*AddOrganizationMemberRequest) Descriptor() ([]byte, []int) {
	return file_wippy_registry_identity_v1_organization_membership_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddOrganizationMemberRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AddOrganizationMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddOrganizationMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created membership.
	Membership    *OrganizationMembership `protobuf:"bytes,1,opt,name=membership,proto3" json:"membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrganizationMemberResponse) Reset() {
	*x = AddOrganizationMemberResponse{}
	mi := &file_wippy_registry_identity_v1_organization_membership_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrganizationMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrganizationMemberResponse) ProtoMessage() {}

func (x *AddOrganizationMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_identity_v1_organization_membership_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrganizationMemberResponse.ProtoReflect.Descriptor instead.
func (*AddOrganizationMemberResponse) Descriptor() ([]byte, []int) {
	return file_wippy_registry_identity_v1_organization_membership_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddOrganizationMemberResponse) GetMembership() *OrganizationMembership {
	if x != nil {
		return x.Membership
	}
	return nil
}

var File_wippy_registry_identity_v1_organization_membership_service_proto protoreflect.FileDescriptor

const file_wippy_registry_identity_v1_organization_membership_service_proto_rawDesc = "" +
	"\n" +
	"@wippy/registry/identity/v1/organization_membership_service.proto\x12\x1awippy.registry.identity.v1\x1a\x1bbuf/validate/validate.proto\x1a8wippy/registry/identity/v1/organization_membership.proto\"z\n" +
	"\x1cAddOrganizationMemberRequest\x124\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0eorganizationId\x12$\n" +
	"\auser_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06userId\"s\n" +
	"\x1dAddOrganizationMemberResponse\x12R\n" +
	"\n" +
	"membership\x18\x01 \x01(\v22.wippy.registry.identity.v1.OrganizationMembershipR\n" +
	"membership2\xb3\x01\n" +
	"\x1dOrganizationMembershipService\x12\x91\x01\n" +
	"\x15AddOrganizationMember\x128.wippy.registry.identity.v1.AddOrganizationMemberRequest\x1a9.wippy.registry.identity.v1.AddOrganizationMemberResponse\"\x03\x90\x02\x02BMZKgithub.com/wippyai/module-registry-proto-go/registry/identity/v1;identityv1b\x06proto3"

var (
	file_wippy_registry_identity_v1_organization_membership_service_proto_rawDescOnce sync.Once
	file_wippy_registry_identity_v1_organization_membership_service_proto_rawDescData []byte
)

func file_wippy_registry_identity_v1_organization_membership_service_proto_rawDescGZIP() []byte {
	file_wippy_registry_identity_v1_organization_membership_service_proto_rawDescOnce.Do(func() {
		file_wippy_registry_identity_v1_organization_membership_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_organization_membership_service_proto_rawDesc), len(file_wippy_registry_identity_v1_organization_membership_service_proto_rawDesc)))
	})
	return file_wippy_registry_identity_v1_organization_membership_service_proto_rawDescData
}

var file_wippy_registry_identity_v1_organization_membership_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wippy_registry_identity_v1_organization_membership_service_proto_goTypes = []any{
	(*AddOrganizationMemberRequest)(nil),  // 0: wippy.registry.identity.v1.AddOrganizationMemberRequest
	(*AddOrganizationMemberResponse)(nil), // 1: wippy.registry.identity.v1.AddOrganizationMemberResponse
	(*OrganizationMembership)(nil),        // 2: wippy.registry.identity.v1.OrganizationMembership
}
var file_wippy_registry_identity_v1_organization_membership_service_proto_depIdxs = []int32{
	2, // 0: wippy.registry.identity.v1.AddOrganizationMemberResponse.membership:type_name -> wippy.registry.identity.v1.OrganizationMembership
	0, // 1: wippy.registry.identity.v1.OrganizationMembershipService.AddOrganizationMember:input_type -> wippy.registry.identity.v1.AddOrganizationMemberRequest
	1, // 2: wippy.registry.identity.v1.OrganizationMembershipService.AddOrganizationMember:output_type -> wippy.registry.identity.v1.AddOrganizationMemberResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wippy_registry_identity_v1_organization_membership_service_proto_init() }
func file_wippy_registry_identity_v1_organization_membership_service_proto_init() {
	if File_wippy_registry_identity_v1_organization_membership_service_proto != nil {
		return
	}
	file_wippy_registry_identity_v1_organization_membership_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_organization_membership_service_proto_rawDesc), len(file_wippy_registry_identity_v1_organization_membership_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_registry_identity_v1_organization_membership_service_proto_goTypes,
		DependencyIndexes: file_wippy_registry_identity_v1_organization_membership_service_proto_depIdxs,
		MessageInfos:      file_wippy_registry_identity_v1_organization_membership_service_proto_msgTypes,
	}.Build()
	File_wippy_registry_identity_v1_organization_membership_service_proto = out.File
	file_wippy_registry_identity_v1_organization_membership_service_proto_goTypes = nil
	file_wippy_registry_identity_v1_organization_membership_service_proto_depIdxs = nil
}
