// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wippy/registry/identity/v1/organization_role.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role of a user in an organization.
type OrganizationRole int32

const (
	// Unspecified role.
	OrganizationRole_ORGANIZATION_ROLE_UNSPECIFIED OrganizationRole = 0
	// Owner role - can manage organization and all members.
	OrganizationRole_ORGANIZATION_ROLE_OWNER OrganizationRole = 1
	// Regular member role - limited permissions.
	OrganizationRole_ORGANIZATION_ROLE_MEMBER OrganizationRole = 2
)

// Enum value maps for OrganizationRole.
var (
	OrganizationRole_name = map[int32]string{
		0: "ORGANIZATION_ROLE_UNSPECIFIED",
		1: "ORGANIZATION_ROLE_OWNER",
		2: "ORGANIZATION_ROLE_MEMBER",
	}
	OrganizationRole_value = map[string]int32{
		"ORGANIZATION_ROLE_UNSPECIFIED": 0,
		"ORGANIZATION_ROLE_OWNER":       1,
		"ORGANIZATION_ROLE_MEMBER":      2,
	}
)

func (x OrganizationRole) Enum() *OrganizationRole {
	p := new(OrganizationRole)
	*p = x
	return p
}

func (x OrganizationRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrganizationRole) Descriptor() protoreflect.EnumDescriptor {
	return file_wippy_registry_identity_v1_organization_role_proto_enumTypes[0].Descriptor()
}

func (OrganizationRole) Type() protoreflect.EnumType {
	return &file_wippy_registry_identity_v1_organization_role_proto_enumTypes[0]
}

func (x OrganizationRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrganizationRole.Descriptor instead.
func (OrganizationRole) EnumDescriptor() ([]byte, []int) {
	return file_wippy_registry_identity_v1_organization_role_proto_rawDescGZIP(), []int{0}
}

var File_wippy_registry_identity_v1_organization_role_proto protoreflect.FileDescriptor

const file_wippy_registry_identity_v1_organization_role_proto_rawDesc = "" +
	"\n" +
	"2wippy/registry/identity/v1/organization_role.proto\x12\x1awippy.registry.identity.v1*p\n" +
	"\x10OrganizationRole\x12!\n" +
	"\x1dORGANIZATION_ROLE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ORGANIZATION_ROLE_OWNER\x10\x01\x12\x1c\n" +
	"\x18ORGANIZATION_ROLE_MEMBER\x10\x02BMZKgithub.com/wippyai/module-registry-proto-go/registry/identity/v1;identityv1b\x06proto3"

var (
	file_wippy_registry_identity_v1_organization_role_proto_rawDescOnce sync.Once
	file_wippy_registry_identity_v1_organization_role_proto_rawDescData []byte
)

func file_wippy_registry_identity_v1_organization_role_proto_rawDescGZIP() []byte {
	file_wippy_registry_identity_v1_organization_role_proto_rawDescOnce.Do(func() {
		file_wippy_registry_identity_v1_organization_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_organization_role_proto_rawDesc), len(file_wippy_registry_identity_v1_organization_role_proto_rawDesc)))
	})
	return file_wippy_registry_identity_v1_organization_role_proto_rawDescData
}

var file_wippy_registry_identity_v1_organization_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wippy_registry_identity_v1_organization_role_proto_goTypes = []any{
	(OrganizationRole)(0), // 0: wippy.registry.identity.v1.OrganizationRole
}
var file_wippy_registry_identity_v1_organization_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wippy_registry_identity_v1_organization_role_proto_init() }
func file_wippy_registry_identity_v1_organization_role_proto_init() {
	if File_wippy_registry_identity_v1_organization_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_organization_role_proto_rawDesc), len(file_wippy_registry_identity_v1_organization_role_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wippy_registry_identity_v1_organization_role_proto_goTypes,
		DependencyIndexes: file_wippy_registry_identity_v1_organization_role_proto_depIdxs,
		EnumInfos:         file_wippy_registry_identity_v1_organization_role_proto_enumTypes,
	}.Build()
	File_wippy_registry_identity_v1_organization_role_proto = out.File
	file_wippy_registry_identity_v1_organization_role_proto_goTypes = nil
	file_wippy_registry_identity_v1_organization_role_proto_depIdxs = nil
}
