// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wippy/registry/identity/v1/user.proto

package identityv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User in registry.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id for the User.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The time the User was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last time the User was updated.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// The name of the User.
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_wippy_registry_identity_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_identity_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_wippy_registry_identity_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *User) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_wippy_registry_identity_v1_user_proto protoreflect.FileDescriptor

const file_wippy_registry_identity_v1_user_proto_rawDesc = "" +
	"\n" +
	"%wippy/registry/identity/v1/user.proto\x12\x1awippy.registry.identity.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x01\n" +
	"\x04User\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\x12C\n" +
	"\vcreate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"createTime\x12C\n" +
	"\vupdate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"updateTime\x12;\n" +
	"\x04name\x18\x04 \x01(\tB'\xbaH$\xc8\x01\x01r\x1f\x10\x02\x18 2\x19^[a-z][a-z0-9-]*[a-z0-9]$R\x04nameBMZKgithub.com/wippyai/module-registry-proto-go/registry/identity/v1;identityv1b\x06proto3"

var (
	file_wippy_registry_identity_v1_user_proto_rawDescOnce sync.Once
	file_wippy_registry_identity_v1_user_proto_rawDescData []byte
)

func file_wippy_registry_identity_v1_user_proto_rawDescGZIP() []byte {
	file_wippy_registry_identity_v1_user_proto_rawDescOnce.Do(func() {
		file_wippy_registry_identity_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_user_proto_rawDesc), len(file_wippy_registry_identity_v1_user_proto_rawDesc)))
	})
	return file_wippy_registry_identity_v1_user_proto_rawDescData
}

var file_wippy_registry_identity_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wippy_registry_identity_v1_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: wippy.registry.identity.v1.User
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_wippy_registry_identity_v1_user_proto_depIdxs = []int32{
	1, // 0: wippy.registry.identity.v1.User.create_time:type_name -> google.protobuf.Timestamp
	1, // 1: wippy.registry.identity.v1.User.update_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wippy_registry_identity_v1_user_proto_init() }
func file_wippy_registry_identity_v1_user_proto_init() {
	if File_wippy_registry_identity_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_user_proto_rawDesc), len(file_wippy_registry_identity_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wippy_registry_identity_v1_user_proto_goTypes,
		DependencyIndexes: file_wippy_registry_identity_v1_user_proto_depIdxs,
		MessageInfos:      file_wippy_registry_identity_v1_user_proto_msgTypes,
	}.Build()
	File_wippy_registry_identity_v1_user_proto = out.File
	file_wippy_registry_identity_v1_user_proto_goTypes = nil
	file_wippy_registry_identity_v1_user_proto_depIdxs = nil
}
