// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wippy/registry/identity/v1/user_service.proto

package identityv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to get the currently authenticated user.
type SelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfRequest) Reset() {
	*x = SelfRequest{}
	mi := &file_wippy_registry_identity_v1_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfRequest) ProtoMessage() {}

func (x *SelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_identity_v1_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfRequest.ProtoReflect.Descriptor instead.
func (*SelfRequest) Descriptor() ([]byte, []int) {
	return file_wippy_registry_identity_v1_user_service_proto_rawDescGZIP(), []int{0}
}

// Response containing the authenticated user's information.
type SelfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfResponse) Reset() {
	*x = SelfResponse{}
	mi := &file_wippy_registry_identity_v1_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfResponse) ProtoMessage() {}

func (x *SelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_identity_v1_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfResponse.ProtoReflect.Descriptor instead.
func (*SelfResponse) Descriptor() ([]byte, []int) {
	return file_wippy_registry_identity_v1_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *SelfResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_wippy_registry_identity_v1_user_service_proto protoreflect.FileDescriptor

const file_wippy_registry_identity_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"-wippy/registry/identity/v1/user_service.proto\x12\x1awippy.registry.identity.v1\x1a\x1bbuf/validate/validate.proto\x1a%wippy/registry/identity/v1/user.proto\"\r\n" +
	"\vSelfRequest\"D\n" +
	"\fSelfResponse\x124\n" +
	"\x04user\x18\x01 \x01(\v2 .wippy.registry.identity.v1.UserR\x04user2m\n" +
	"\vUserService\x12^\n" +
	"\x04Self\x12'.wippy.registry.identity.v1.SelfRequest\x1a(.wippy.registry.identity.v1.SelfResponse\"\x03\x90\x02\x01BMZKgithub.com/wippyai/module-registry-proto-go/registry/identity/v1;identityv1b\x06proto3"

var (
	file_wippy_registry_identity_v1_user_service_proto_rawDescOnce sync.Once
	file_wippy_registry_identity_v1_user_service_proto_rawDescData []byte
)

func file_wippy_registry_identity_v1_user_service_proto_rawDescGZIP() []byte {
	file_wippy_registry_identity_v1_user_service_proto_rawDescOnce.Do(func() {
		file_wippy_registry_identity_v1_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_user_service_proto_rawDesc), len(file_wippy_registry_identity_v1_user_service_proto_rawDesc)))
	})
	return file_wippy_registry_identity_v1_user_service_proto_rawDescData
}

var file_wippy_registry_identity_v1_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wippy_registry_identity_v1_user_service_proto_goTypes = []any{
	(*SelfRequest)(nil),  // 0: wippy.registry.identity.v1.SelfRequest
	(*SelfResponse)(nil), // 1: wippy.registry.identity.v1.SelfResponse
	(*User)(nil),         // 2: wippy.registry.identity.v1.User
}
var file_wippy_registry_identity_v1_user_service_proto_depIdxs = []int32{
	2, // 0: wippy.registry.identity.v1.SelfResponse.user:type_name -> wippy.registry.identity.v1.User
	0, // 1: wippy.registry.identity.v1.UserService.Self:input_type -> wippy.registry.identity.v1.SelfRequest
	1, // 2: wippy.registry.identity.v1.UserService.Self:output_type -> wippy.registry.identity.v1.SelfResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wippy_registry_identity_v1_user_service_proto_init() }
func file_wippy_registry_identity_v1_user_service_proto_init() {
	if File_wippy_registry_identity_v1_user_service_proto != nil {
		return
	}
	file_wippy_registry_identity_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_registry_identity_v1_user_service_proto_rawDesc), len(file_wippy_registry_identity_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_registry_identity_v1_user_service_proto_goTypes,
		DependencyIndexes: file_wippy_registry_identity_v1_user_service_proto_depIdxs,
		MessageInfos:      file_wippy_registry_identity_v1_user_service_proto_msgTypes,
	}.Build()
	File_wippy_registry_identity_v1_user_service_proto = out.File
	file_wippy_registry_identity_v1_user_service_proto_goTypes = nil
	file_wippy_registry_identity_v1_user_service_proto_depIdxs = nil
}
