// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wippy/hub/module/v1/download_service.proto

package modulev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wippyai/proto-api/wippy/hub/module/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DownloadServiceName is the fully-qualified name of the DownloadService service.
	DownloadServiceName = "wippy.hub.module.v1.DownloadService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DownloadServiceGetDownloadURLProcedure is the fully-qualified name of the DownloadService's
	// GetDownloadURL RPC.
	DownloadServiceGetDownloadURLProcedure = "/wippy.hub.module.v1.DownloadService/GetDownloadURL"
	// DownloadServiceGetBatchDownloadURLsProcedure is the fully-qualified name of the DownloadService's
	// GetBatchDownloadURLs RPC.
	DownloadServiceGetBatchDownloadURLsProcedure = "/wippy.hub.module.v1.DownloadService/GetBatchDownloadURLs"
	// DownloadServiceGetReadmeProcedure is the fully-qualified name of the DownloadService's GetReadme
	// RPC.
	DownloadServiceGetReadmeProcedure = "/wippy.hub.module.v1.DownloadService/GetReadme"
)

// DownloadServiceClient is a client for the wippy.hub.module.v1.DownloadService service.
type DownloadServiceClient interface {
	// Get a download URL for a module version.
	// Returns a pre-signed S3 URL valid for a limited time.
	GetDownloadURL(context.Context, *connect.Request[v1.GetDownloadURLRequest]) (*connect.Response[v1.GetDownloadURLResponse], error)
	// Get download URLs for multiple modules at once.
	// Used for batch dependency resolution.
	GetBatchDownloadURLs(context.Context, *connect.Request[v1.GetBatchDownloadURLsRequest]) (*connect.Response[v1.GetBatchDownloadURLsResponse], error)
	// Get README content for a module version.
	GetReadme(context.Context, *connect.Request[v1.GetReadmeRequest]) (*connect.Response[v1.GetReadmeResponse], error)
}

// NewDownloadServiceClient constructs a client for the wippy.hub.module.v1.DownloadService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDownloadServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DownloadServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	downloadServiceMethods := v1.File_wippy_hub_module_v1_download_service_proto.Services().ByName("DownloadService").Methods()
	return &downloadServiceClient{
		getDownloadURL: connect.NewClient[v1.GetDownloadURLRequest, v1.GetDownloadURLResponse](
			httpClient,
			baseURL+DownloadServiceGetDownloadURLProcedure,
			connect.WithSchema(downloadServiceMethods.ByName("GetDownloadURL")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getBatchDownloadURLs: connect.NewClient[v1.GetBatchDownloadURLsRequest, v1.GetBatchDownloadURLsResponse](
			httpClient,
			baseURL+DownloadServiceGetBatchDownloadURLsProcedure,
			connect.WithSchema(downloadServiceMethods.ByName("GetBatchDownloadURLs")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getReadme: connect.NewClient[v1.GetReadmeRequest, v1.GetReadmeResponse](
			httpClient,
			baseURL+DownloadServiceGetReadmeProcedure,
			connect.WithSchema(downloadServiceMethods.ByName("GetReadme")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// downloadServiceClient implements DownloadServiceClient.
type downloadServiceClient struct {
	getDownloadURL       *connect.Client[v1.GetDownloadURLRequest, v1.GetDownloadURLResponse]
	getBatchDownloadURLs *connect.Client[v1.GetBatchDownloadURLsRequest, v1.GetBatchDownloadURLsResponse]
	getReadme            *connect.Client[v1.GetReadmeRequest, v1.GetReadmeResponse]
}

// GetDownloadURL calls wippy.hub.module.v1.DownloadService.GetDownloadURL.
func (c *downloadServiceClient) GetDownloadURL(ctx context.Context, req *connect.Request[v1.GetDownloadURLRequest]) (*connect.Response[v1.GetDownloadURLResponse], error) {
	return c.getDownloadURL.CallUnary(ctx, req)
}

// GetBatchDownloadURLs calls wippy.hub.module.v1.DownloadService.GetBatchDownloadURLs.
func (c *downloadServiceClient) GetBatchDownloadURLs(ctx context.Context, req *connect.Request[v1.GetBatchDownloadURLsRequest]) (*connect.Response[v1.GetBatchDownloadURLsResponse], error) {
	return c.getBatchDownloadURLs.CallUnary(ctx, req)
}

// GetReadme calls wippy.hub.module.v1.DownloadService.GetReadme.
func (c *downloadServiceClient) GetReadme(ctx context.Context, req *connect.Request[v1.GetReadmeRequest]) (*connect.Response[v1.GetReadmeResponse], error) {
	return c.getReadme.CallUnary(ctx, req)
}

// DownloadServiceHandler is an implementation of the wippy.hub.module.v1.DownloadService service.
type DownloadServiceHandler interface {
	// Get a download URL for a module version.
	// Returns a pre-signed S3 URL valid for a limited time.
	GetDownloadURL(context.Context, *connect.Request[v1.GetDownloadURLRequest]) (*connect.Response[v1.GetDownloadURLResponse], error)
	// Get download URLs for multiple modules at once.
	// Used for batch dependency resolution.
	GetBatchDownloadURLs(context.Context, *connect.Request[v1.GetBatchDownloadURLsRequest]) (*connect.Response[v1.GetBatchDownloadURLsResponse], error)
	// Get README content for a module version.
	GetReadme(context.Context, *connect.Request[v1.GetReadmeRequest]) (*connect.Response[v1.GetReadmeResponse], error)
}

// NewDownloadServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDownloadServiceHandler(svc DownloadServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	downloadServiceMethods := v1.File_wippy_hub_module_v1_download_service_proto.Services().ByName("DownloadService").Methods()
	downloadServiceGetDownloadURLHandler := connect.NewUnaryHandler(
		DownloadServiceGetDownloadURLProcedure,
		svc.GetDownloadURL,
		connect.WithSchema(downloadServiceMethods.ByName("GetDownloadURL")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	downloadServiceGetBatchDownloadURLsHandler := connect.NewUnaryHandler(
		DownloadServiceGetBatchDownloadURLsProcedure,
		svc.GetBatchDownloadURLs,
		connect.WithSchema(downloadServiceMethods.ByName("GetBatchDownloadURLs")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	downloadServiceGetReadmeHandler := connect.NewUnaryHandler(
		DownloadServiceGetReadmeProcedure,
		svc.GetReadme,
		connect.WithSchema(downloadServiceMethods.ByName("GetReadme")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/wippy.hub.module.v1.DownloadService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DownloadServiceGetDownloadURLProcedure:
			downloadServiceGetDownloadURLHandler.ServeHTTP(w, r)
		case DownloadServiceGetBatchDownloadURLsProcedure:
			downloadServiceGetBatchDownloadURLsHandler.ServeHTTP(w, r)
		case DownloadServiceGetReadmeProcedure:
			downloadServiceGetReadmeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDownloadServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDownloadServiceHandler struct{}

func (UnimplementedDownloadServiceHandler) GetDownloadURL(context.Context, *connect.Request[v1.GetDownloadURLRequest]) (*connect.Response[v1.GetDownloadURLResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.DownloadService.GetDownloadURL is not implemented"))
}

func (UnimplementedDownloadServiceHandler) GetBatchDownloadURLs(context.Context, *connect.Request[v1.GetBatchDownloadURLsRequest]) (*connect.Response[v1.GetBatchDownloadURLsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.DownloadService.GetBatchDownloadURLs is not implemented"))
}

func (UnimplementedDownloadServiceHandler) GetReadme(context.Context, *connect.Request[v1.GetReadmeRequest]) (*connect.Response[v1.GetReadmeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.DownloadService.GetReadme is not implemented"))
}
