// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wippy/hub/module/v1/module_service.proto

package modulev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wippyai/proto-api/wippy/hub/module/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ModuleServiceName is the fully-qualified name of the ModuleService service.
	ModuleServiceName = "wippy.hub.module.v1.ModuleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ModuleServiceCreateModuleProcedure is the fully-qualified name of the ModuleService's
	// CreateModule RPC.
	ModuleServiceCreateModuleProcedure = "/wippy.hub.module.v1.ModuleService/CreateModule"
	// ModuleServiceGetModuleProcedure is the fully-qualified name of the ModuleService's GetModule RPC.
	ModuleServiceGetModuleProcedure = "/wippy.hub.module.v1.ModuleService/GetModule"
	// ModuleServiceListModulesProcedure is the fully-qualified name of the ModuleService's ListModules
	// RPC.
	ModuleServiceListModulesProcedure = "/wippy.hub.module.v1.ModuleService/ListModules"
	// ModuleServiceUpdateModuleProcedure is the fully-qualified name of the ModuleService's
	// UpdateModule RPC.
	ModuleServiceUpdateModuleProcedure = "/wippy.hub.module.v1.ModuleService/UpdateModule"
	// ModuleServiceDeleteModuleProcedure is the fully-qualified name of the ModuleService's
	// DeleteModule RPC.
	ModuleServiceDeleteModuleProcedure = "/wippy.hub.module.v1.ModuleService/DeleteModule"
	// ModuleServiceDeprecateModuleProcedure is the fully-qualified name of the ModuleService's
	// DeprecateModule RPC.
	ModuleServiceDeprecateModuleProcedure = "/wippy.hub.module.v1.ModuleService/DeprecateModule"
	// ModuleServiceSearchModulesProcedure is the fully-qualified name of the ModuleService's
	// SearchModules RPC.
	ModuleServiceSearchModulesProcedure = "/wippy.hub.module.v1.ModuleService/SearchModules"
	// ModuleServiceListVersionsProcedure is the fully-qualified name of the ModuleService's
	// ListVersions RPC.
	ModuleServiceListVersionsProcedure = "/wippy.hub.module.v1.ModuleService/ListVersions"
	// ModuleServiceGetVersionProcedure is the fully-qualified name of the ModuleService's GetVersion
	// RPC.
	ModuleServiceGetVersionProcedure = "/wippy.hub.module.v1.ModuleService/GetVersion"
	// ModuleServiceListVersionFilesProcedure is the fully-qualified name of the ModuleService's
	// ListVersionFiles RPC.
	ModuleServiceListVersionFilesProcedure = "/wippy.hub.module.v1.ModuleService/ListVersionFiles"
	// ModuleServiceGetDependenciesProcedure is the fully-qualified name of the ModuleService's
	// GetDependencies RPC.
	ModuleServiceGetDependenciesProcedure = "/wippy.hub.module.v1.ModuleService/GetDependencies"
	// ModuleServiceGetDependentsProcedure is the fully-qualified name of the ModuleService's
	// GetDependents RPC.
	ModuleServiceGetDependentsProcedure = "/wippy.hub.module.v1.ModuleService/GetDependents"
)

// ModuleServiceClient is a client for the wippy.hub.module.v1.ModuleService service.
type ModuleServiceClient interface {
	// Create a new module.
	CreateModule(context.Context, *connect.Request[v1.CreateModuleRequest]) (*connect.Response[v1.CreateModuleResponse], error)
	// Get a module by ID or name.
	GetModule(context.Context, *connect.Request[v1.GetModuleRequest]) (*connect.Response[v1.GetModuleResponse], error)
	// List modules with filtering.
	ListModules(context.Context, *connect.Request[v1.ListModulesRequest]) (*connect.Response[v1.ListModulesResponse], error)
	// Update module settings.
	UpdateModule(context.Context, *connect.Request[v1.UpdateModuleRequest]) (*connect.Response[v1.UpdateModuleResponse], error)
	// Delete a module.
	DeleteModule(context.Context, *connect.Request[v1.DeleteModuleRequest]) (*connect.Response[v1.DeleteModuleResponse], error)
	// Deprecate a module.
	DeprecateModule(context.Context, *connect.Request[v1.DeprecateModuleRequest]) (*connect.Response[v1.DeprecateModuleResponse], error)
	// Search modules.
	SearchModules(context.Context, *connect.Request[v1.SearchModulesRequest]) (*connect.Response[v1.SearchModulesResponse], error)
	// List versions of a module.
	ListVersions(context.Context, *connect.Request[v1.ListVersionsRequest]) (*connect.Response[v1.ListVersionsResponse], error)
	// Get a specific version.
	GetVersion(context.Context, *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error)
	// List files in a version.
	ListVersionFiles(context.Context, *connect.Request[v1.ListVersionFilesRequest]) (*connect.Response[v1.ListVersionFilesResponse], error)
	// Get module dependencies.
	GetDependencies(context.Context, *connect.Request[v1.GetDependenciesRequest]) (*connect.Response[v1.GetDependenciesResponse], error)
	// Get modules that depend on this one.
	GetDependents(context.Context, *connect.Request[v1.GetDependentsRequest]) (*connect.Response[v1.GetDependentsResponse], error)
}

// NewModuleServiceClient constructs a client for the wippy.hub.module.v1.ModuleService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewModuleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ModuleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	moduleServiceMethods := v1.File_wippy_hub_module_v1_module_service_proto.Services().ByName("ModuleService").Methods()
	return &moduleServiceClient{
		createModule: connect.NewClient[v1.CreateModuleRequest, v1.CreateModuleResponse](
			httpClient,
			baseURL+ModuleServiceCreateModuleProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("CreateModule")),
			connect.WithClientOptions(opts...),
		),
		getModule: connect.NewClient[v1.GetModuleRequest, v1.GetModuleResponse](
			httpClient,
			baseURL+ModuleServiceGetModuleProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("GetModule")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listModules: connect.NewClient[v1.ListModulesRequest, v1.ListModulesResponse](
			httpClient,
			baseURL+ModuleServiceListModulesProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("ListModules")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateModule: connect.NewClient[v1.UpdateModuleRequest, v1.UpdateModuleResponse](
			httpClient,
			baseURL+ModuleServiceUpdateModuleProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("UpdateModule")),
			connect.WithClientOptions(opts...),
		),
		deleteModule: connect.NewClient[v1.DeleteModuleRequest, v1.DeleteModuleResponse](
			httpClient,
			baseURL+ModuleServiceDeleteModuleProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("DeleteModule")),
			connect.WithClientOptions(opts...),
		),
		deprecateModule: connect.NewClient[v1.DeprecateModuleRequest, v1.DeprecateModuleResponse](
			httpClient,
			baseURL+ModuleServiceDeprecateModuleProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("DeprecateModule")),
			connect.WithClientOptions(opts...),
		),
		searchModules: connect.NewClient[v1.SearchModulesRequest, v1.SearchModulesResponse](
			httpClient,
			baseURL+ModuleServiceSearchModulesProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("SearchModules")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listVersions: connect.NewClient[v1.ListVersionsRequest, v1.ListVersionsResponse](
			httpClient,
			baseURL+ModuleServiceListVersionsProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("ListVersions")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getVersion: connect.NewClient[v1.GetVersionRequest, v1.GetVersionResponse](
			httpClient,
			baseURL+ModuleServiceGetVersionProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("GetVersion")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listVersionFiles: connect.NewClient[v1.ListVersionFilesRequest, v1.ListVersionFilesResponse](
			httpClient,
			baseURL+ModuleServiceListVersionFilesProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("ListVersionFiles")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getDependencies: connect.NewClient[v1.GetDependenciesRequest, v1.GetDependenciesResponse](
			httpClient,
			baseURL+ModuleServiceGetDependenciesProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("GetDependencies")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getDependents: connect.NewClient[v1.GetDependentsRequest, v1.GetDependentsResponse](
			httpClient,
			baseURL+ModuleServiceGetDependentsProcedure,
			connect.WithSchema(moduleServiceMethods.ByName("GetDependents")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// moduleServiceClient implements ModuleServiceClient.
type moduleServiceClient struct {
	createModule     *connect.Client[v1.CreateModuleRequest, v1.CreateModuleResponse]
	getModule        *connect.Client[v1.GetModuleRequest, v1.GetModuleResponse]
	listModules      *connect.Client[v1.ListModulesRequest, v1.ListModulesResponse]
	updateModule     *connect.Client[v1.UpdateModuleRequest, v1.UpdateModuleResponse]
	deleteModule     *connect.Client[v1.DeleteModuleRequest, v1.DeleteModuleResponse]
	deprecateModule  *connect.Client[v1.DeprecateModuleRequest, v1.DeprecateModuleResponse]
	searchModules    *connect.Client[v1.SearchModulesRequest, v1.SearchModulesResponse]
	listVersions     *connect.Client[v1.ListVersionsRequest, v1.ListVersionsResponse]
	getVersion       *connect.Client[v1.GetVersionRequest, v1.GetVersionResponse]
	listVersionFiles *connect.Client[v1.ListVersionFilesRequest, v1.ListVersionFilesResponse]
	getDependencies  *connect.Client[v1.GetDependenciesRequest, v1.GetDependenciesResponse]
	getDependents    *connect.Client[v1.GetDependentsRequest, v1.GetDependentsResponse]
}

// CreateModule calls wippy.hub.module.v1.ModuleService.CreateModule.
func (c *moduleServiceClient) CreateModule(ctx context.Context, req *connect.Request[v1.CreateModuleRequest]) (*connect.Response[v1.CreateModuleResponse], error) {
	return c.createModule.CallUnary(ctx, req)
}

// GetModule calls wippy.hub.module.v1.ModuleService.GetModule.
func (c *moduleServiceClient) GetModule(ctx context.Context, req *connect.Request[v1.GetModuleRequest]) (*connect.Response[v1.GetModuleResponse], error) {
	return c.getModule.CallUnary(ctx, req)
}

// ListModules calls wippy.hub.module.v1.ModuleService.ListModules.
func (c *moduleServiceClient) ListModules(ctx context.Context, req *connect.Request[v1.ListModulesRequest]) (*connect.Response[v1.ListModulesResponse], error) {
	return c.listModules.CallUnary(ctx, req)
}

// UpdateModule calls wippy.hub.module.v1.ModuleService.UpdateModule.
func (c *moduleServiceClient) UpdateModule(ctx context.Context, req *connect.Request[v1.UpdateModuleRequest]) (*connect.Response[v1.UpdateModuleResponse], error) {
	return c.updateModule.CallUnary(ctx, req)
}

// DeleteModule calls wippy.hub.module.v1.ModuleService.DeleteModule.
func (c *moduleServiceClient) DeleteModule(ctx context.Context, req *connect.Request[v1.DeleteModuleRequest]) (*connect.Response[v1.DeleteModuleResponse], error) {
	return c.deleteModule.CallUnary(ctx, req)
}

// DeprecateModule calls wippy.hub.module.v1.ModuleService.DeprecateModule.
func (c *moduleServiceClient) DeprecateModule(ctx context.Context, req *connect.Request[v1.DeprecateModuleRequest]) (*connect.Response[v1.DeprecateModuleResponse], error) {
	return c.deprecateModule.CallUnary(ctx, req)
}

// SearchModules calls wippy.hub.module.v1.ModuleService.SearchModules.
func (c *moduleServiceClient) SearchModules(ctx context.Context, req *connect.Request[v1.SearchModulesRequest]) (*connect.Response[v1.SearchModulesResponse], error) {
	return c.searchModules.CallUnary(ctx, req)
}

// ListVersions calls wippy.hub.module.v1.ModuleService.ListVersions.
func (c *moduleServiceClient) ListVersions(ctx context.Context, req *connect.Request[v1.ListVersionsRequest]) (*connect.Response[v1.ListVersionsResponse], error) {
	return c.listVersions.CallUnary(ctx, req)
}

// GetVersion calls wippy.hub.module.v1.ModuleService.GetVersion.
func (c *moduleServiceClient) GetVersion(ctx context.Context, req *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error) {
	return c.getVersion.CallUnary(ctx, req)
}

// ListVersionFiles calls wippy.hub.module.v1.ModuleService.ListVersionFiles.
func (c *moduleServiceClient) ListVersionFiles(ctx context.Context, req *connect.Request[v1.ListVersionFilesRequest]) (*connect.Response[v1.ListVersionFilesResponse], error) {
	return c.listVersionFiles.CallUnary(ctx, req)
}

// GetDependencies calls wippy.hub.module.v1.ModuleService.GetDependencies.
func (c *moduleServiceClient) GetDependencies(ctx context.Context, req *connect.Request[v1.GetDependenciesRequest]) (*connect.Response[v1.GetDependenciesResponse], error) {
	return c.getDependencies.CallUnary(ctx, req)
}

// GetDependents calls wippy.hub.module.v1.ModuleService.GetDependents.
func (c *moduleServiceClient) GetDependents(ctx context.Context, req *connect.Request[v1.GetDependentsRequest]) (*connect.Response[v1.GetDependentsResponse], error) {
	return c.getDependents.CallUnary(ctx, req)
}

// ModuleServiceHandler is an implementation of the wippy.hub.module.v1.ModuleService service.
type ModuleServiceHandler interface {
	// Create a new module.
	CreateModule(context.Context, *connect.Request[v1.CreateModuleRequest]) (*connect.Response[v1.CreateModuleResponse], error)
	// Get a module by ID or name.
	GetModule(context.Context, *connect.Request[v1.GetModuleRequest]) (*connect.Response[v1.GetModuleResponse], error)
	// List modules with filtering.
	ListModules(context.Context, *connect.Request[v1.ListModulesRequest]) (*connect.Response[v1.ListModulesResponse], error)
	// Update module settings.
	UpdateModule(context.Context, *connect.Request[v1.UpdateModuleRequest]) (*connect.Response[v1.UpdateModuleResponse], error)
	// Delete a module.
	DeleteModule(context.Context, *connect.Request[v1.DeleteModuleRequest]) (*connect.Response[v1.DeleteModuleResponse], error)
	// Deprecate a module.
	DeprecateModule(context.Context, *connect.Request[v1.DeprecateModuleRequest]) (*connect.Response[v1.DeprecateModuleResponse], error)
	// Search modules.
	SearchModules(context.Context, *connect.Request[v1.SearchModulesRequest]) (*connect.Response[v1.SearchModulesResponse], error)
	// List versions of a module.
	ListVersions(context.Context, *connect.Request[v1.ListVersionsRequest]) (*connect.Response[v1.ListVersionsResponse], error)
	// Get a specific version.
	GetVersion(context.Context, *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error)
	// List files in a version.
	ListVersionFiles(context.Context, *connect.Request[v1.ListVersionFilesRequest]) (*connect.Response[v1.ListVersionFilesResponse], error)
	// Get module dependencies.
	GetDependencies(context.Context, *connect.Request[v1.GetDependenciesRequest]) (*connect.Response[v1.GetDependenciesResponse], error)
	// Get modules that depend on this one.
	GetDependents(context.Context, *connect.Request[v1.GetDependentsRequest]) (*connect.Response[v1.GetDependentsResponse], error)
}

// NewModuleServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewModuleServiceHandler(svc ModuleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	moduleServiceMethods := v1.File_wippy_hub_module_v1_module_service_proto.Services().ByName("ModuleService").Methods()
	moduleServiceCreateModuleHandler := connect.NewUnaryHandler(
		ModuleServiceCreateModuleProcedure,
		svc.CreateModule,
		connect.WithSchema(moduleServiceMethods.ByName("CreateModule")),
		connect.WithHandlerOptions(opts...),
	)
	moduleServiceGetModuleHandler := connect.NewUnaryHandler(
		ModuleServiceGetModuleProcedure,
		svc.GetModule,
		connect.WithSchema(moduleServiceMethods.ByName("GetModule")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	moduleServiceListModulesHandler := connect.NewUnaryHandler(
		ModuleServiceListModulesProcedure,
		svc.ListModules,
		connect.WithSchema(moduleServiceMethods.ByName("ListModules")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	moduleServiceUpdateModuleHandler := connect.NewUnaryHandler(
		ModuleServiceUpdateModuleProcedure,
		svc.UpdateModule,
		connect.WithSchema(moduleServiceMethods.ByName("UpdateModule")),
		connect.WithHandlerOptions(opts...),
	)
	moduleServiceDeleteModuleHandler := connect.NewUnaryHandler(
		ModuleServiceDeleteModuleProcedure,
		svc.DeleteModule,
		connect.WithSchema(moduleServiceMethods.ByName("DeleteModule")),
		connect.WithHandlerOptions(opts...),
	)
	moduleServiceDeprecateModuleHandler := connect.NewUnaryHandler(
		ModuleServiceDeprecateModuleProcedure,
		svc.DeprecateModule,
		connect.WithSchema(moduleServiceMethods.ByName("DeprecateModule")),
		connect.WithHandlerOptions(opts...),
	)
	moduleServiceSearchModulesHandler := connect.NewUnaryHandler(
		ModuleServiceSearchModulesProcedure,
		svc.SearchModules,
		connect.WithSchema(moduleServiceMethods.ByName("SearchModules")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	moduleServiceListVersionsHandler := connect.NewUnaryHandler(
		ModuleServiceListVersionsProcedure,
		svc.ListVersions,
		connect.WithSchema(moduleServiceMethods.ByName("ListVersions")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	moduleServiceGetVersionHandler := connect.NewUnaryHandler(
		ModuleServiceGetVersionProcedure,
		svc.GetVersion,
		connect.WithSchema(moduleServiceMethods.ByName("GetVersion")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	moduleServiceListVersionFilesHandler := connect.NewUnaryHandler(
		ModuleServiceListVersionFilesProcedure,
		svc.ListVersionFiles,
		connect.WithSchema(moduleServiceMethods.ByName("ListVersionFiles")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	moduleServiceGetDependenciesHandler := connect.NewUnaryHandler(
		ModuleServiceGetDependenciesProcedure,
		svc.GetDependencies,
		connect.WithSchema(moduleServiceMethods.ByName("GetDependencies")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	moduleServiceGetDependentsHandler := connect.NewUnaryHandler(
		ModuleServiceGetDependentsProcedure,
		svc.GetDependents,
		connect.WithSchema(moduleServiceMethods.ByName("GetDependents")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/wippy.hub.module.v1.ModuleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ModuleServiceCreateModuleProcedure:
			moduleServiceCreateModuleHandler.ServeHTTP(w, r)
		case ModuleServiceGetModuleProcedure:
			moduleServiceGetModuleHandler.ServeHTTP(w, r)
		case ModuleServiceListModulesProcedure:
			moduleServiceListModulesHandler.ServeHTTP(w, r)
		case ModuleServiceUpdateModuleProcedure:
			moduleServiceUpdateModuleHandler.ServeHTTP(w, r)
		case ModuleServiceDeleteModuleProcedure:
			moduleServiceDeleteModuleHandler.ServeHTTP(w, r)
		case ModuleServiceDeprecateModuleProcedure:
			moduleServiceDeprecateModuleHandler.ServeHTTP(w, r)
		case ModuleServiceSearchModulesProcedure:
			moduleServiceSearchModulesHandler.ServeHTTP(w, r)
		case ModuleServiceListVersionsProcedure:
			moduleServiceListVersionsHandler.ServeHTTP(w, r)
		case ModuleServiceGetVersionProcedure:
			moduleServiceGetVersionHandler.ServeHTTP(w, r)
		case ModuleServiceListVersionFilesProcedure:
			moduleServiceListVersionFilesHandler.ServeHTTP(w, r)
		case ModuleServiceGetDependenciesProcedure:
			moduleServiceGetDependenciesHandler.ServeHTTP(w, r)
		case ModuleServiceGetDependentsProcedure:
			moduleServiceGetDependentsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedModuleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedModuleServiceHandler struct{}

func (UnimplementedModuleServiceHandler) CreateModule(context.Context, *connect.Request[v1.CreateModuleRequest]) (*connect.Response[v1.CreateModuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.CreateModule is not implemented"))
}

func (UnimplementedModuleServiceHandler) GetModule(context.Context, *connect.Request[v1.GetModuleRequest]) (*connect.Response[v1.GetModuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.GetModule is not implemented"))
}

func (UnimplementedModuleServiceHandler) ListModules(context.Context, *connect.Request[v1.ListModulesRequest]) (*connect.Response[v1.ListModulesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.ListModules is not implemented"))
}

func (UnimplementedModuleServiceHandler) UpdateModule(context.Context, *connect.Request[v1.UpdateModuleRequest]) (*connect.Response[v1.UpdateModuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.UpdateModule is not implemented"))
}

func (UnimplementedModuleServiceHandler) DeleteModule(context.Context, *connect.Request[v1.DeleteModuleRequest]) (*connect.Response[v1.DeleteModuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.DeleteModule is not implemented"))
}

func (UnimplementedModuleServiceHandler) DeprecateModule(context.Context, *connect.Request[v1.DeprecateModuleRequest]) (*connect.Response[v1.DeprecateModuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.DeprecateModule is not implemented"))
}

func (UnimplementedModuleServiceHandler) SearchModules(context.Context, *connect.Request[v1.SearchModulesRequest]) (*connect.Response[v1.SearchModulesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.SearchModules is not implemented"))
}

func (UnimplementedModuleServiceHandler) ListVersions(context.Context, *connect.Request[v1.ListVersionsRequest]) (*connect.Response[v1.ListVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.ListVersions is not implemented"))
}

func (UnimplementedModuleServiceHandler) GetVersion(context.Context, *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.GetVersion is not implemented"))
}

func (UnimplementedModuleServiceHandler) ListVersionFiles(context.Context, *connect.Request[v1.ListVersionFilesRequest]) (*connect.Response[v1.ListVersionFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.ListVersionFiles is not implemented"))
}

func (UnimplementedModuleServiceHandler) GetDependencies(context.Context, *connect.Request[v1.GetDependenciesRequest]) (*connect.Response[v1.GetDependenciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.GetDependencies is not implemented"))
}

func (UnimplementedModuleServiceHandler) GetDependents(context.Context, *connect.Request[v1.GetDependentsRequest]) (*connect.Response[v1.GetDependentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wippy.hub.module.v1.ModuleService.GetDependents is not implemented"))
}
