// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/hub/module/v1/download_service.proto

package modulev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for download URL.
type GetDownloadURLRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module reference.
	//
	// Types that are valid to be assigned to Module:
	//
	//	*GetDownloadURLRequest_ModuleId
	//	*GetDownloadURLRequest_ModuleName
	Module isGetDownloadURLRequest_Module `protobuf_oneof:"module"`
	// Version reference.
	Version       *VersionRef `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLRequest) Reset() {
	*x = GetDownloadURLRequest{}
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLRequest) ProtoMessage() {}

func (x *GetDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_download_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetDownloadURLRequest) GetModule() isGetDownloadURLRequest_Module {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *GetDownloadURLRequest) GetModuleId() string {
	if x != nil {
		if x, ok := x.Module.(*GetDownloadURLRequest_ModuleId); ok {
			return x.ModuleId
		}
	}
	return ""
}

func (x *GetDownloadURLRequest) GetModuleName() *ModuleName {
	if x != nil {
		if x, ok := x.Module.(*GetDownloadURLRequest_ModuleName); ok {
			return x.ModuleName
		}
	}
	return nil
}

func (x *GetDownloadURLRequest) GetVersion() *VersionRef {
	if x != nil {
		return x.Version
	}
	return nil
}

type isGetDownloadURLRequest_Module interface {
	isGetDownloadURLRequest_Module()
}

type GetDownloadURLRequest_ModuleId struct {
	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3,oneof"`
}

type GetDownloadURLRequest_ModuleName struct {
	ModuleName *ModuleName `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3,oneof"`
}

func (*GetDownloadURLRequest_ModuleId) isGetDownloadURLRequest_Module() {}

func (*GetDownloadURLRequest_ModuleName) isGetDownloadURLRequest_Module() {}

// Response with download URL.
type GetDownloadURLResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pre-signed download URL.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// URL expiration time.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// SHA-256 digest for verification.
	Digest string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	// File size in bytes.
	SizeBytes uint64 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Version information.
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Whether the module is protected (WAPP format, not unpacked).
	Protected     bool `protobuf:"varint,6,opt,name=protected,proto3" json:"protected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLResponse) Reset() {
	*x = GetDownloadURLResponse{}
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLResponse) ProtoMessage() {}

func (x *GetDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_download_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetDownloadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetDownloadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GetDownloadURLResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *GetDownloadURLResponse) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *GetDownloadURLResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetDownloadURLResponse) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

// Request for batch download URLs.
type GetBatchDownloadURLsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Modules to get download URLs for.
	Items         []*BatchDownloadItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchDownloadURLsRequest) Reset() {
	*x = GetBatchDownloadURLsRequest{}
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchDownloadURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchDownloadURLsRequest) ProtoMessage() {}

func (x *GetBatchDownloadURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchDownloadURLsRequest.ProtoReflect.Descriptor instead.
func (*GetBatchDownloadURLsRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_download_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBatchDownloadURLsRequest) GetItems() []*BatchDownloadItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Single item in batch download request.
type BatchDownloadItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Org   string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Version constraint or specific version.
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDownloadItem) Reset() {
	*x = BatchDownloadItem{}
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDownloadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDownloadItem) ProtoMessage() {}

func (x *BatchDownloadItem) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDownloadItem.ProtoReflect.Descriptor instead.
func (*BatchDownloadItem) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_download_service_proto_rawDescGZIP(), []int{3}
}

func (x *BatchDownloadItem) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *BatchDownloadItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BatchDownloadItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Response with batch download URLs.
type GetBatchDownloadURLsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Download URLs for each requested module.
	Results       []*BatchDownloadResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchDownloadURLsResponse) Reset() {
	*x = GetBatchDownloadURLsResponse{}
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchDownloadURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchDownloadURLsResponse) ProtoMessage() {}

func (x *GetBatchDownloadURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchDownloadURLsResponse.ProtoReflect.Descriptor instead.
func (*GetBatchDownloadURLsResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_download_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetBatchDownloadURLsResponse) GetResults() []*BatchDownloadResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// Result for single item in batch download.
type BatchDownloadResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Org   string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Resolved version.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Pre-signed download URL.
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// URL expiration.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// SHA-256 digest.
	Digest string `protobuf:"bytes,6,opt,name=digest,proto3" json:"digest,omitempty"`
	// File size.
	SizeBytes uint64 `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Whether protected.
	Protected bool `protobuf:"varint,8,opt,name=protected,proto3" json:"protected,omitempty"`
	// Error if resolution failed.
	Error         string `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDownloadResult) Reset() {
	*x = BatchDownloadResult{}
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDownloadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDownloadResult) ProtoMessage() {}

func (x *BatchDownloadResult) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDownloadResult.ProtoReflect.Descriptor instead.
func (*BatchDownloadResult) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_download_service_proto_rawDescGZIP(), []int{5}
}

func (x *BatchDownloadResult) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *BatchDownloadResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BatchDownloadResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BatchDownloadResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BatchDownloadResult) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *BatchDownloadResult) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *BatchDownloadResult) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BatchDownloadResult) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *BatchDownloadResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request for README.
type GetReadmeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Module:
	//
	//	*GetReadmeRequest_ModuleId
	//	*GetReadmeRequest_ModuleName
	Module isGetReadmeRequest_Module `protobuf_oneof:"module"`
	// Version reference (optional, defaults to latest).
	Version       *VersionRef `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadmeRequest) Reset() {
	*x = GetReadmeRequest{}
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadmeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadmeRequest) ProtoMessage() {}

func (x *GetReadmeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadmeRequest.ProtoReflect.Descriptor instead.
func (*GetReadmeRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_download_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetReadmeRequest) GetModule() isGetReadmeRequest_Module {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *GetReadmeRequest) GetModuleId() string {
	if x != nil {
		if x, ok := x.Module.(*GetReadmeRequest_ModuleId); ok {
			return x.ModuleId
		}
	}
	return ""
}

func (x *GetReadmeRequest) GetModuleName() *ModuleName {
	if x != nil {
		if x, ok := x.Module.(*GetReadmeRequest_ModuleName); ok {
			return x.ModuleName
		}
	}
	return nil
}

func (x *GetReadmeRequest) GetVersion() *VersionRef {
	if x != nil {
		return x.Version
	}
	return nil
}

type isGetReadmeRequest_Module interface {
	isGetReadmeRequest_Module()
}

type GetReadmeRequest_ModuleId struct {
	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3,oneof"`
}

type GetReadmeRequest_ModuleName struct {
	ModuleName *ModuleName `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3,oneof"`
}

func (*GetReadmeRequest_ModuleId) isGetReadmeRequest_Module() {}

func (*GetReadmeRequest_ModuleName) isGetReadmeRequest_Module() {}

// Response with README content.
type GetReadmeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// README content (markdown).
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// README filename.
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	// Version this README belongs to.
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadmeResponse) Reset() {
	*x = GetReadmeResponse{}
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadmeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadmeResponse) ProtoMessage() {}

func (x *GetReadmeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_download_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadmeResponse.ProtoReflect.Descriptor instead.
func (*GetReadmeResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_download_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetReadmeResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetReadmeResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetReadmeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_wippy_hub_module_v1_download_service_proto protoreflect.FileDescriptor

const file_wippy_hub_module_v1_download_service_proto_rawDesc = "" +
	"\n" +
	"*wippy/hub/module/v1/download_service.proto\x12\x13wippy.hub.module.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!wippy/hub/module/v1/version.proto\x1a)wippy/hub/module/v1/publish_service.proto\"\xc9\x01\n" +
	"\x15GetDownloadURLRequest\x12'\n" +
	"\tmodule_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\bmoduleId\x12B\n" +
	"\vmodule_name\x18\x02 \x01(\v2\x1f.wippy.hub.module.v1.ModuleNameH\x00R\n" +
	"moduleName\x129\n" +
	"\aversion\x18\x03 \x01(\v2\x1f.wippy.hub.module.v1.VersionRefR\aversionB\b\n" +
	"\x06module\"\xd4\x01\n" +
	"\x16GetDownloadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1c\n" +
	"\tprotected\x18\x06 \x01(\bR\tprotected\"g\n" +
	"\x1bGetBatchDownloadURLsRequest\x12H\n" +
	"\x05items\x18\x01 \x03(\v2&.wippy.hub.module.v1.BatchDownloadItemB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x102R\x05items\"e\n" +
	"\x11BatchDownloadItem\x12\x19\n" +
	"\x03org\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03org\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"b\n" +
	"\x1cGetBatchDownloadURLsResponse\x12B\n" +
	"\aresults\x18\x01 \x03(\v2(.wippy.hub.module.v1.BatchDownloadResultR\aresults\"\x8d\x02\n" +
	"\x13BatchDownloadResult\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06digest\x18\x06 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x04R\tsizeBytes\x12\x1c\n" +
	"\tprotected\x18\b \x01(\bR\tprotected\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\"\xc4\x01\n" +
	"\x10GetReadmeRequest\x12'\n" +
	"\tmodule_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\bmoduleId\x12B\n" +
	"\vmodule_name\x18\x02 \x01(\v2\x1f.wippy.hub.module.v1.ModuleNameH\x00R\n" +
	"moduleName\x129\n" +
	"\aversion\x18\x03 \x01(\v2\x1f.wippy.hub.module.v1.VersionRefR\aversionB\b\n" +
	"\x06module\"c\n" +
	"\x11GetReadmeResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\xe5\x02\n" +
	"\x0fDownloadService\x12n\n" +
	"\x0eGetDownloadURL\x12*.wippy.hub.module.v1.GetDownloadURLRequest\x1a+.wippy.hub.module.v1.GetDownloadURLResponse\"\x03\x90\x02\x01\x12\x80\x01\n" +
	"\x14GetBatchDownloadURLs\x120.wippy.hub.module.v1.GetBatchDownloadURLsRequest\x1a1.wippy.hub.module.v1.GetBatchDownloadURLsResponse\"\x03\x90\x02\x01\x12_\n" +
	"\tGetReadme\x12%.wippy.hub.module.v1.GetReadmeRequest\x1a&.wippy.hub.module.v1.GetReadmeResponse\"\x03\x90\x02\x01B;Z9github.com/wippyai/proto-api/wippy/hub/module/v1;modulev1b\x06proto3"

var (
	file_wippy_hub_module_v1_download_service_proto_rawDescOnce sync.Once
	file_wippy_hub_module_v1_download_service_proto_rawDescData []byte
)

func file_wippy_hub_module_v1_download_service_proto_rawDescGZIP() []byte {
	file_wippy_hub_module_v1_download_service_proto_rawDescOnce.Do(func() {
		file_wippy_hub_module_v1_download_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_hub_module_v1_download_service_proto_rawDesc), len(file_wippy_hub_module_v1_download_service_proto_rawDesc)))
	})
	return file_wippy_hub_module_v1_download_service_proto_rawDescData
}

var file_wippy_hub_module_v1_download_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wippy_hub_module_v1_download_service_proto_goTypes = []any{
	(*GetDownloadURLRequest)(nil),        // 0: wippy.hub.module.v1.GetDownloadURLRequest
	(*GetDownloadURLResponse)(nil),       // 1: wippy.hub.module.v1.GetDownloadURLResponse
	(*GetBatchDownloadURLsRequest)(nil),  // 2: wippy.hub.module.v1.GetBatchDownloadURLsRequest
	(*BatchDownloadItem)(nil),            // 3: wippy.hub.module.v1.BatchDownloadItem
	(*GetBatchDownloadURLsResponse)(nil), // 4: wippy.hub.module.v1.GetBatchDownloadURLsResponse
	(*BatchDownloadResult)(nil),          // 5: wippy.hub.module.v1.BatchDownloadResult
	(*GetReadmeRequest)(nil),             // 6: wippy.hub.module.v1.GetReadmeRequest
	(*GetReadmeResponse)(nil),            // 7: wippy.hub.module.v1.GetReadmeResponse
	(*ModuleName)(nil),                   // 8: wippy.hub.module.v1.ModuleName
	(*VersionRef)(nil),                   // 9: wippy.hub.module.v1.VersionRef
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
}
var file_wippy_hub_module_v1_download_service_proto_depIdxs = []int32{
	8,  // 0: wippy.hub.module.v1.GetDownloadURLRequest.module_name:type_name -> wippy.hub.module.v1.ModuleName
	9,  // 1: wippy.hub.module.v1.GetDownloadURLRequest.version:type_name -> wippy.hub.module.v1.VersionRef
	10, // 2: wippy.hub.module.v1.GetDownloadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 3: wippy.hub.module.v1.GetBatchDownloadURLsRequest.items:type_name -> wippy.hub.module.v1.BatchDownloadItem
	5,  // 4: wippy.hub.module.v1.GetBatchDownloadURLsResponse.results:type_name -> wippy.hub.module.v1.BatchDownloadResult
	10, // 5: wippy.hub.module.v1.BatchDownloadResult.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 6: wippy.hub.module.v1.GetReadmeRequest.module_name:type_name -> wippy.hub.module.v1.ModuleName
	9,  // 7: wippy.hub.module.v1.GetReadmeRequest.version:type_name -> wippy.hub.module.v1.VersionRef
	0,  // 8: wippy.hub.module.v1.DownloadService.GetDownloadURL:input_type -> wippy.hub.module.v1.GetDownloadURLRequest
	2,  // 9: wippy.hub.module.v1.DownloadService.GetBatchDownloadURLs:input_type -> wippy.hub.module.v1.GetBatchDownloadURLsRequest
	6,  // 10: wippy.hub.module.v1.DownloadService.GetReadme:input_type -> wippy.hub.module.v1.GetReadmeRequest
	1,  // 11: wippy.hub.module.v1.DownloadService.GetDownloadURL:output_type -> wippy.hub.module.v1.GetDownloadURLResponse
	4,  // 12: wippy.hub.module.v1.DownloadService.GetBatchDownloadURLs:output_type -> wippy.hub.module.v1.GetBatchDownloadURLsResponse
	7,  // 13: wippy.hub.module.v1.DownloadService.GetReadme:output_type -> wippy.hub.module.v1.GetReadmeResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_wippy_hub_module_v1_download_service_proto_init() }
func file_wippy_hub_module_v1_download_service_proto_init() {
	if File_wippy_hub_module_v1_download_service_proto != nil {
		return
	}
	file_wippy_hub_module_v1_version_proto_init()
	file_wippy_hub_module_v1_publish_service_proto_init()
	file_wippy_hub_module_v1_download_service_proto_msgTypes[0].OneofWrappers = []any{
		(*GetDownloadURLRequest_ModuleId)(nil),
		(*GetDownloadURLRequest_ModuleName)(nil),
	}
	file_wippy_hub_module_v1_download_service_proto_msgTypes[6].OneofWrappers = []any{
		(*GetReadmeRequest_ModuleId)(nil),
		(*GetReadmeRequest_ModuleName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_hub_module_v1_download_service_proto_rawDesc), len(file_wippy_hub_module_v1_download_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_hub_module_v1_download_service_proto_goTypes,
		DependencyIndexes: file_wippy_hub_module_v1_download_service_proto_depIdxs,
		MessageInfos:      file_wippy_hub_module_v1_download_service_proto_msgTypes,
	}.Build()
	File_wippy_hub_module_v1_download_service_proto = out.File
	file_wippy_hub_module_v1_download_service_proto_goTypes = nil
	file_wippy_hub_module_v1_download_service_proto_depIdxs = nil
}
