// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/hub/module/v1/label_service.proto

package modulev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to set a label.
type SetLabelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module reference.
	Module *ModuleRef `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// Label name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Version to point to.
	Version       *VersionRef `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLabelRequest) Reset() {
	*x = SetLabelRequest{}
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLabelRequest) ProtoMessage() {}

func (x *SetLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLabelRequest.ProtoReflect.Descriptor instead.
func (*SetLabelRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_label_service_proto_rawDescGZIP(), []int{0}
}

func (x *SetLabelRequest) GetModule() *ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *SetLabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetLabelRequest) GetVersion() *VersionRef {
	if x != nil {
		return x.Version
	}
	return nil
}

// Response for set label.
type SetLabelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         *Label                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLabelResponse) Reset() {
	*x = SetLabelResponse{}
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLabelResponse) ProtoMessage() {}

func (x *SetLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLabelResponse.ProtoReflect.Descriptor instead.
func (*SetLabelResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_label_service_proto_rawDescGZIP(), []int{1}
}

func (x *SetLabelResponse) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

// Request to delete a label.
type DeleteLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ModuleRef             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLabelRequest) Reset() {
	*x = DeleteLabelRequest{}
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLabelRequest) ProtoMessage() {}

func (x *DeleteLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLabelRequest.ProtoReflect.Descriptor instead.
func (*DeleteLabelRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_label_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteLabelRequest) GetModule() *ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *DeleteLabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response for delete label.
type DeleteLabelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLabelResponse) Reset() {
	*x = DeleteLabelResponse{}
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLabelResponse) ProtoMessage() {}

func (x *DeleteLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLabelResponse.ProtoReflect.Descriptor instead.
func (*DeleteLabelResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_label_service_proto_rawDescGZIP(), []int{3}
}

// Request to get a label.
type GetLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ModuleRef             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLabelRequest) Reset() {
	*x = GetLabelRequest{}
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabelRequest) ProtoMessage() {}

func (x *GetLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabelRequest.ProtoReflect.Descriptor instead.
func (*GetLabelRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_label_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetLabelRequest) GetModule() *ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *GetLabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response for get label.
type GetLabelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         *Label                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Version       *Version               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLabelResponse) Reset() {
	*x = GetLabelResponse{}
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabelResponse) ProtoMessage() {}

func (x *GetLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabelResponse.ProtoReflect.Descriptor instead.
func (*GetLabelResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_label_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetLabelResponse) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *GetLabelResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

// Request to list labels.
type ListLabelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ModuleRef             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabelsRequest) Reset() {
	*x = ListLabelsRequest{}
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabelsRequest) ProtoMessage() {}

func (x *ListLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabelsRequest.ProtoReflect.Descriptor instead.
func (*ListLabelsRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_label_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListLabelsRequest) GetModule() *ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

// Response for list labels.
type ListLabelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*Label               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabelsResponse) Reset() {
	*x = ListLabelsResponse{}
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabelsResponse) ProtoMessage() {}

func (x *ListLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_label_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabelsResponse.ProtoReflect.Descriptor instead.
func (*ListLabelsResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_label_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListLabelsResponse) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_wippy_hub_module_v1_label_service_proto protoreflect.FileDescriptor

const file_wippy_hub_module_v1_label_service_proto_rawDesc = "" +
	"\n" +
	"'wippy/hub/module/v1/label_service.proto\x12\x13wippy.hub.module.v1\x1a\x1bbuf/validate/validate.proto\x1a wippy/hub/module/v1/module.proto\x1a!wippy/hub/module/v1/version.proto\"\xc6\x01\n" +
	"\x0fSetLabelRequest\x12>\n" +
	"\x06module\x18\x01 \x01(\v2\x1e.wippy.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x120\n" +
	"\x04name\x18\x02 \x01(\tB\x1c\xbaH\x19r\x17\x10\x01\x18 2\x11^[a-z][a-z0-9-]*$R\x04name\x12A\n" +
	"\aversion\x18\x03 \x01(\v2\x1f.wippy.hub.module.v1.VersionRefB\x06\xbaH\x03\xc8\x01\x01R\aversion\"D\n" +
	"\x10SetLabelResponse\x120\n" +
	"\x05label\x18\x01 \x01(\v2\x1a.wippy.hub.module.v1.LabelR\x05label\"q\n" +
	"\x12DeleteLabelRequest\x12>\n" +
	"\x06module\x18\x01 \x01(\v2\x1e.wippy.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"\x15\n" +
	"\x13DeleteLabelResponse\"n\n" +
	"\x0fGetLabelRequest\x12>\n" +
	"\x06module\x18\x01 \x01(\v2\x1e.wippy.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"|\n" +
	"\x10GetLabelResponse\x120\n" +
	"\x05label\x18\x01 \x01(\v2\x1a.wippy.hub.module.v1.LabelR\x05label\x126\n" +
	"\aversion\x18\x02 \x01(\v2\x1c.wippy.hub.module.v1.VersionR\aversion\"S\n" +
	"\x11ListLabelsRequest\x12>\n" +
	"\x06module\x18\x01 \x01(\v2\x1e.wippy.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\"H\n" +
	"\x12ListLabelsResponse\x122\n" +
	"\x06labels\x18\x01 \x03(\v2\x1a.wippy.hub.module.v1.LabelR\x06labels2\x92\x03\n" +
	"\fLabelService\x12\\\n" +
	"\bSetLabel\x12$.wippy.hub.module.v1.SetLabelRequest\x1a%.wippy.hub.module.v1.SetLabelResponse\"\x03\x90\x02\x02\x12b\n" +
	"\vDeleteLabel\x12'.wippy.hub.module.v1.DeleteLabelRequest\x1a(.wippy.hub.module.v1.DeleteLabelResponse\"\x00\x12\\\n" +
	"\bGetLabel\x12$.wippy.hub.module.v1.GetLabelRequest\x1a%.wippy.hub.module.v1.GetLabelResponse\"\x03\x90\x02\x01\x12b\n" +
	"\n" +
	"ListLabels\x12&.wippy.hub.module.v1.ListLabelsRequest\x1a'.wippy.hub.module.v1.ListLabelsResponse\"\x03\x90\x02\x01B;Z9github.com/wippyai/proto-api/wippy/hub/module/v1;modulev1b\x06proto3"

var (
	file_wippy_hub_module_v1_label_service_proto_rawDescOnce sync.Once
	file_wippy_hub_module_v1_label_service_proto_rawDescData []byte
)

func file_wippy_hub_module_v1_label_service_proto_rawDescGZIP() []byte {
	file_wippy_hub_module_v1_label_service_proto_rawDescOnce.Do(func() {
		file_wippy_hub_module_v1_label_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_hub_module_v1_label_service_proto_rawDesc), len(file_wippy_hub_module_v1_label_service_proto_rawDesc)))
	})
	return file_wippy_hub_module_v1_label_service_proto_rawDescData
}

var file_wippy_hub_module_v1_label_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wippy_hub_module_v1_label_service_proto_goTypes = []any{
	(*SetLabelRequest)(nil),     // 0: wippy.hub.module.v1.SetLabelRequest
	(*SetLabelResponse)(nil),    // 1: wippy.hub.module.v1.SetLabelResponse
	(*DeleteLabelRequest)(nil),  // 2: wippy.hub.module.v1.DeleteLabelRequest
	(*DeleteLabelResponse)(nil), // 3: wippy.hub.module.v1.DeleteLabelResponse
	(*GetLabelRequest)(nil),     // 4: wippy.hub.module.v1.GetLabelRequest
	(*GetLabelResponse)(nil),    // 5: wippy.hub.module.v1.GetLabelResponse
	(*ListLabelsRequest)(nil),   // 6: wippy.hub.module.v1.ListLabelsRequest
	(*ListLabelsResponse)(nil),  // 7: wippy.hub.module.v1.ListLabelsResponse
	(*ModuleRef)(nil),           // 8: wippy.hub.module.v1.ModuleRef
	(*VersionRef)(nil),          // 9: wippy.hub.module.v1.VersionRef
	(*Label)(nil),               // 10: wippy.hub.module.v1.Label
	(*Version)(nil),             // 11: wippy.hub.module.v1.Version
}
var file_wippy_hub_module_v1_label_service_proto_depIdxs = []int32{
	8,  // 0: wippy.hub.module.v1.SetLabelRequest.module:type_name -> wippy.hub.module.v1.ModuleRef
	9,  // 1: wippy.hub.module.v1.SetLabelRequest.version:type_name -> wippy.hub.module.v1.VersionRef
	10, // 2: wippy.hub.module.v1.SetLabelResponse.label:type_name -> wippy.hub.module.v1.Label
	8,  // 3: wippy.hub.module.v1.DeleteLabelRequest.module:type_name -> wippy.hub.module.v1.ModuleRef
	8,  // 4: wippy.hub.module.v1.GetLabelRequest.module:type_name -> wippy.hub.module.v1.ModuleRef
	10, // 5: wippy.hub.module.v1.GetLabelResponse.label:type_name -> wippy.hub.module.v1.Label
	11, // 6: wippy.hub.module.v1.GetLabelResponse.version:type_name -> wippy.hub.module.v1.Version
	8,  // 7: wippy.hub.module.v1.ListLabelsRequest.module:type_name -> wippy.hub.module.v1.ModuleRef
	10, // 8: wippy.hub.module.v1.ListLabelsResponse.labels:type_name -> wippy.hub.module.v1.Label
	0,  // 9: wippy.hub.module.v1.LabelService.SetLabel:input_type -> wippy.hub.module.v1.SetLabelRequest
	2,  // 10: wippy.hub.module.v1.LabelService.DeleteLabel:input_type -> wippy.hub.module.v1.DeleteLabelRequest
	4,  // 11: wippy.hub.module.v1.LabelService.GetLabel:input_type -> wippy.hub.module.v1.GetLabelRequest
	6,  // 12: wippy.hub.module.v1.LabelService.ListLabels:input_type -> wippy.hub.module.v1.ListLabelsRequest
	1,  // 13: wippy.hub.module.v1.LabelService.SetLabel:output_type -> wippy.hub.module.v1.SetLabelResponse
	3,  // 14: wippy.hub.module.v1.LabelService.DeleteLabel:output_type -> wippy.hub.module.v1.DeleteLabelResponse
	5,  // 15: wippy.hub.module.v1.LabelService.GetLabel:output_type -> wippy.hub.module.v1.GetLabelResponse
	7,  // 16: wippy.hub.module.v1.LabelService.ListLabels:output_type -> wippy.hub.module.v1.ListLabelsResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_wippy_hub_module_v1_label_service_proto_init() }
func file_wippy_hub_module_v1_label_service_proto_init() {
	if File_wippy_hub_module_v1_label_service_proto != nil {
		return
	}
	file_wippy_hub_module_v1_module_proto_init()
	file_wippy_hub_module_v1_version_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_hub_module_v1_label_service_proto_rawDesc), len(file_wippy_hub_module_v1_label_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_hub_module_v1_label_service_proto_goTypes,
		DependencyIndexes: file_wippy_hub_module_v1_label_service_proto_depIdxs,
		MessageInfos:      file_wippy_hub_module_v1_label_service_proto_msgTypes,
	}.Build()
	File_wippy_hub_module_v1_label_service_proto = out.File
	file_wippy_hub_module_v1_label_service_proto_goTypes = nil
	file_wippy_hub_module_v1_label_service_proto_depIdxs = nil
}
