// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/hub/module/v1/manifest_service.proto

package modulev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resolution strategy.
type ResolutionStrategy int32

const (
	ResolutionStrategy_RESOLUTION_STRATEGY_UNSPECIFIED ResolutionStrategy = 0
	// Prefer newest compatible versions.
	ResolutionStrategy_RESOLUTION_STRATEGY_NEWEST ResolutionStrategy = 1
	// Prefer minimal version updates.
	ResolutionStrategy_RESOLUTION_STRATEGY_MINIMAL ResolutionStrategy = 2
)

// Enum value maps for ResolutionStrategy.
var (
	ResolutionStrategy_name = map[int32]string{
		0: "RESOLUTION_STRATEGY_UNSPECIFIED",
		1: "RESOLUTION_STRATEGY_NEWEST",
		2: "RESOLUTION_STRATEGY_MINIMAL",
	}
	ResolutionStrategy_value = map[string]int32{
		"RESOLUTION_STRATEGY_UNSPECIFIED": 0,
		"RESOLUTION_STRATEGY_NEWEST":      1,
		"RESOLUTION_STRATEGY_MINIMAL":     2,
	}
)

func (x ResolutionStrategy) Enum() *ResolutionStrategy {
	p := new(ResolutionStrategy)
	*p = x
	return p
}

func (x ResolutionStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolutionStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_wippy_hub_module_v1_manifest_service_proto_enumTypes[0].Descriptor()
}

func (ResolutionStrategy) Type() protoreflect.EnumType {
	return &file_wippy_hub_module_v1_manifest_service_proto_enumTypes[0]
}

func (x ResolutionStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolutionStrategy.Descriptor instead.
func (ResolutionStrategy) EnumDescriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{0}
}

// Request for module manifest.
type GetManifestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module reference.
	//
	// Types that are valid to be assigned to Module:
	//
	//	*GetManifestRequest_ModuleId
	//	*GetManifestRequest_ModuleName
	Module isGetManifestRequest_Module `protobuf_oneof:"module"`
	// Version reference (specific version, label, or constraint).
	Version       *VersionRef `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetManifestRequest) GetModule() isGetManifestRequest_Module {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *GetManifestRequest) GetModuleId() string {
	if x != nil {
		if x, ok := x.Module.(*GetManifestRequest_ModuleId); ok {
			return x.ModuleId
		}
	}
	return ""
}

func (x *GetManifestRequest) GetModuleName() *ModuleName {
	if x != nil {
		if x, ok := x.Module.(*GetManifestRequest_ModuleName); ok {
			return x.ModuleName
		}
	}
	return nil
}

func (x *GetManifestRequest) GetVersion() *VersionRef {
	if x != nil {
		return x.Version
	}
	return nil
}

type isGetManifestRequest_Module interface {
	isGetManifestRequest_Module()
}

type GetManifestRequest_ModuleId struct {
	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3,oneof"`
}

type GetManifestRequest_ModuleName struct {
	ModuleName *ModuleName `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3,oneof"`
}

func (*GetManifestRequest_ModuleId) isGetManifestRequest_Module() {}

func (*GetManifestRequest_ModuleName) isGetManifestRequest_Module() {}

// Response with module manifest.
type GetManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The manifest.
	Manifest      *ModuleManifest `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetManifestResponse) GetManifest() *ModuleManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Complete manifest for a module version.
type ModuleManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module information.
	Module *ModuleInfo `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// Version information.
	Version *VersionInfo `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Direct dependencies.
	Dependencies []*ResolvedDependency `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	// Download information.
	Download      *DownloadInfo `protobuf:"bytes,4,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleManifest) Reset() {
	*x = ModuleManifest{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleManifest) ProtoMessage() {}

func (x *ModuleManifest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleManifest.ProtoReflect.Descriptor instead.
func (*ModuleManifest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleManifest) GetModule() *ModuleInfo {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *ModuleManifest) GetVersion() *VersionInfo {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ModuleManifest) GetDependencies() []*ResolvedDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ModuleManifest) GetDownload() *DownloadInfo {
	if x != nil {
		return x.Download
	}
	return nil
}

// Basic module information.
type ModuleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	License       string                 `protobuf:"bytes,5,opt,name=license,proto3" json:"license,omitempty"`
	Repository    string                 `protobuf:"bytes,6,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleInfo) Reset() {
	*x = ModuleInfo{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleInfo) ProtoMessage() {}

func (x *ModuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleInfo.ProtoReflect.Descriptor instead.
func (*ModuleInfo) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{3}
}

func (x *ModuleInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModuleInfo) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ModuleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModuleInfo) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *ModuleInfo) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

// Version information in manifest.
type VersionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Digest        string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Metadata      *VersionMetadata       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{4}
}

func (x *VersionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VersionInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionInfo) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *VersionInfo) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *VersionInfo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *VersionInfo) GetMetadata() *VersionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Resolved dependency with download info.
type ResolvedDependency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization.
	Org string `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	// Module name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Resolved version.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Version ID.
	VersionId string `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	// SHA-256 digest.
	Digest string `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	// Download URL (pre-signed).
	DownloadUrl string `protobuf:"bytes,6,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	// URL expiration.
	DownloadExpiresAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=download_expires_at,json=downloadExpiresAt,proto3" json:"download_expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolvedDependency) Reset() {
	*x = ResolvedDependency{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedDependency) ProtoMessage() {}

func (x *ResolvedDependency) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedDependency.ProtoReflect.Descriptor instead.
func (*ResolvedDependency) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResolvedDependency) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ResolvedDependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolvedDependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResolvedDependency) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ResolvedDependency) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ResolvedDependency) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ResolvedDependency) GetDownloadExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DownloadExpiresAt
	}
	return nil
}

// Download information.
type DownloadInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pre-signed download URL.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// URL expiration time.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// SHA-256 digest for verification.
	Digest string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	// File size in bytes.
	SizeBytes     uint64 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadInfo) Reset() {
	*x = DownloadInfo{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadInfo) ProtoMessage() {}

func (x *DownloadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadInfo.ProtoReflect.Descriptor instead.
func (*DownloadInfo) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *DownloadInfo) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *DownloadInfo) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// Request to resolve dependencies.
type ResolveDependenciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Root modules to resolve.
	Roots []*DependencySpec `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	// Already installed modules (for incremental resolution).
	Installed []*InstalledModule `protobuf:"bytes,2,rep,name=installed,proto3" json:"installed,omitempty"`
	// Resolution strategy.
	Strategy      ResolutionStrategy `protobuf:"varint,3,opt,name=strategy,proto3,enum=wippy.hub.module.v1.ResolutionStrategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDependenciesRequest) Reset() {
	*x = ResolveDependenciesRequest{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDependenciesRequest) ProtoMessage() {}

func (x *ResolveDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDependenciesRequest.ProtoReflect.Descriptor instead.
func (*ResolveDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveDependenciesRequest) GetRoots() []*DependencySpec {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *ResolveDependenciesRequest) GetInstalled() []*InstalledModule {
	if x != nil {
		return x.Installed
	}
	return nil
}

func (x *ResolveDependenciesRequest) GetStrategy() ResolutionStrategy {
	if x != nil {
		return x.Strategy
	}
	return ResolutionStrategy_RESOLUTION_STRATEGY_UNSPECIFIED
}

// Dependency specification.
type DependencySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Org   string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Version constraint (semver range).
	Constraint    string `protobuf:"bytes,3,opt,name=constraint,proto3" json:"constraint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencySpec) Reset() {
	*x = DependencySpec{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencySpec) ProtoMessage() {}

func (x *DependencySpec) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencySpec.ProtoReflect.Descriptor instead.
func (*DependencySpec) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{8}
}

func (x *DependencySpec) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *DependencySpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DependencySpec) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

// Already installed module.
type InstalledModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledModule) Reset() {
	*x = InstalledModule{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledModule) ProtoMessage() {}

func (x *InstalledModule) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledModule.ProtoReflect.Descriptor instead.
func (*InstalledModule) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{9}
}

func (x *InstalledModule) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *InstalledModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstalledModule) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledModule) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// Response with resolved dependencies.
type ResolveDependenciesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All modules to install/update.
	Modules []*ResolvedModule `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	// Resolution errors (if any).
	Errors        []*ResolutionError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDependenciesResponse) Reset() {
	*x = ResolveDependenciesResponse{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDependenciesResponse) ProtoMessage() {}

func (x *ResolveDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDependenciesResponse.ProtoReflect.Descriptor instead.
func (*ResolveDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveDependenciesResponse) GetModules() []*ResolvedModule {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *ResolveDependenciesResponse) GetErrors() []*ResolutionError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Resolved module with full download info.
type ResolvedModule struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Org               string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version           string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	VersionId         string                 `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Digest            string                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	SizeBytes         uint64                 `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	DownloadUrl       string                 `protobuf:"bytes,7,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	DownloadExpiresAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=download_expires_at,json=downloadExpiresAt,proto3" json:"download_expires_at,omitempty"`
	// Dependencies of this module.
	Dependencies  []*DependencySpec `protobuf:"bytes,9,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedModule) Reset() {
	*x = ResolvedModule{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedModule) ProtoMessage() {}

func (x *ResolvedModule) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedModule.ProtoReflect.Descriptor instead.
func (*ResolvedModule) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{11}
}

func (x *ResolvedModule) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ResolvedModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolvedModule) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResolvedModule) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ResolvedModule) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ResolvedModule) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ResolvedModule) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ResolvedModule) GetDownloadExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DownloadExpiresAt
	}
	return nil
}

func (x *ResolvedModule) GetDependencies() []*DependencySpec {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

// Resolution error.
type ResolutionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Constraint    string                 `protobuf:"bytes,3,opt,name=constraint,proto3" json:"constraint,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolutionError) Reset() {
	*x = ResolutionError{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolutionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolutionError) ProtoMessage() {}

func (x *ResolutionError) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolutionError.ProtoReflect.Descriptor instead.
func (*ResolutionError) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{12}
}

func (x *ResolutionError) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ResolutionError) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolutionError) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

func (x *ResolutionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResolutionError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Request to check for updates.
type CheckUpdatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Currently installed modules.
	Installed     []*InstalledModule `protobuf:"bytes,1,rep,name=installed,proto3" json:"installed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUpdatesRequest) Reset() {
	*x = CheckUpdatesRequest{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdatesRequest) ProtoMessage() {}

func (x *CheckUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdatesRequest.ProtoReflect.Descriptor instead.
func (*CheckUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{13}
}

func (x *CheckUpdatesRequest) GetInstalled() []*InstalledModule {
	if x != nil {
		return x.Installed
	}
	return nil
}

// Response with available updates.
type CheckUpdatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Available updates.
	Updates       []*ModuleUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUpdatesResponse) Reset() {
	*x = CheckUpdatesResponse{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdatesResponse) ProtoMessage() {}

func (x *CheckUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdatesResponse.ProtoReflect.Descriptor instead.
func (*CheckUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{14}
}

func (x *CheckUpdatesResponse) GetUpdates() []*ModuleUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

// Available module update.
type ModuleUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Org            string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrentVersion string                 `protobuf:"bytes,3,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	LatestVersion  string                 `protobuf:"bytes,4,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	// Whether this is a breaking change.
	Breaking bool `protobuf:"varint,5,opt,name=breaking,proto3" json:"breaking,omitempty"`
	// Update summary.
	Summary       string `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleUpdate) Reset() {
	*x = ModuleUpdate{}
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleUpdate) ProtoMessage() {}

func (x *ModuleUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_manifest_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleUpdate.ProtoReflect.Descriptor instead.
func (*ModuleUpdate) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP(), []int{15}
}

func (x *ModuleUpdate) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ModuleUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleUpdate) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *ModuleUpdate) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *ModuleUpdate) GetBreaking() bool {
	if x != nil {
		return x.Breaking
	}
	return false
}

func (x *ModuleUpdate) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_wippy_hub_module_v1_manifest_service_proto protoreflect.FileDescriptor

const file_wippy_hub_module_v1_manifest_service_proto_rawDesc = "" +
	"\n" +
	"*wippy/hub/module/v1/manifest_service.proto\x12\x13wippy.hub.module.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!wippy/hub/module/v1/version.proto\x1a)wippy/hub/module/v1/publish_service.proto\"\xc6\x01\n" +
	"\x12GetManifestRequest\x12'\n" +
	"\tmodule_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\bmoduleId\x12B\n" +
	"\vmodule_name\x18\x02 \x01(\v2\x1f.wippy.hub.module.v1.ModuleNameH\x00R\n" +
	"moduleName\x129\n" +
	"\aversion\x18\x03 \x01(\v2\x1f.wippy.hub.module.v1.VersionRefR\aversionB\b\n" +
	"\x06module\"V\n" +
	"\x13GetManifestResponse\x12?\n" +
	"\bmanifest\x18\x01 \x01(\v2#.wippy.hub.module.v1.ModuleManifestR\bmanifest\"\x91\x02\n" +
	"\x0eModuleManifest\x127\n" +
	"\x06module\x18\x01 \x01(\v2\x1f.wippy.hub.module.v1.ModuleInfoR\x06module\x12:\n" +
	"\aversion\x18\x02 \x01(\v2 .wippy.hub.module.v1.VersionInfoR\aversion\x12K\n" +
	"\fdependencies\x18\x03 \x03(\v2'.wippy.hub.module.v1.ResolvedDependencyR\fdependencies\x12=\n" +
	"\bdownload\x18\x04 \x01(\v2!.wippy.hub.module.v1.DownloadInfoR\bdownload\"\x9e\x01\n" +
	"\n" +
	"ModuleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\alicense\x18\x05 \x01(\tR\alicense\x12\x1e\n" +
	"\n" +
	"repository\x18\x06 \x01(\tR\n" +
	"repository\"\xed\x01\n" +
	"\vVersionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12@\n" +
	"\bmetadata\x18\x06 \x01(\v2$.wippy.hub.module.v1.VersionMetadataR\bmetadata\"\xfa\x01\n" +
	"\x12ResolvedDependency\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tR\tversionId\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x12!\n" +
	"\fdownload_url\x18\x06 \x01(\tR\vdownloadUrl\x12J\n" +
	"\x13download_expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x11downloadExpiresAt\"\x92\x01\n" +
	"\fDownloadInfo\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\"\xea\x01\n" +
	"\x1aResolveDependenciesRequest\x12C\n" +
	"\x05roots\x18\x01 \x03(\v2#.wippy.hub.module.v1.DependencySpecB\b\xbaH\x05\x92\x01\x02\b\x01R\x05roots\x12B\n" +
	"\tinstalled\x18\x02 \x03(\v2$.wippy.hub.module.v1.InstalledModuleR\tinstalled\x12C\n" +
	"\bstrategy\x18\x03 \x01(\x0e2'.wippy.hub.module.v1.ResolutionStrategyR\bstrategy\"h\n" +
	"\x0eDependencySpec\x12\x19\n" +
	"\x03org\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03org\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12\x1e\n" +
	"\n" +
	"constraint\x18\x03 \x01(\tR\n" +
	"constraint\"i\n" +
	"\x0fInstalledModule\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"\x9a\x01\n" +
	"\x1bResolveDependenciesResponse\x12=\n" +
	"\amodules\x18\x01 \x03(\v2#.wippy.hub.module.v1.ResolvedModuleR\amodules\x12<\n" +
	"\x06errors\x18\x02 \x03(\v2$.wippy.hub.module.v1.ResolutionErrorR\x06errors\"\xde\x02\n" +
	"\x0eResolvedModule\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tR\tversionId\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x04R\tsizeBytes\x12!\n" +
	"\fdownload_url\x18\a \x01(\tR\vdownloadUrl\x12J\n" +
	"\x13download_expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11downloadExpiresAt\x12G\n" +
	"\fdependencies\x18\t \x03(\v2#.wippy.hub.module.v1.DependencySpecR\fdependencies\"\x85\x01\n" +
	"\x0fResolutionError\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"constraint\x18\x03 \x01(\tR\n" +
	"constraint\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\"c\n" +
	"\x13CheckUpdatesRequest\x12L\n" +
	"\tinstalled\x18\x01 \x03(\v2$.wippy.hub.module.v1.InstalledModuleB\b\xbaH\x05\x92\x01\x02\b\x01R\tinstalled\"S\n" +
	"\x14CheckUpdatesResponse\x12;\n" +
	"\aupdates\x18\x01 \x03(\v2!.wippy.hub.module.v1.ModuleUpdateR\aupdates\"\xba\x01\n" +
	"\fModuleUpdate\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fcurrent_version\x18\x03 \x01(\tR\x0ecurrentVersion\x12%\n" +
	"\x0elatest_version\x18\x04 \x01(\tR\rlatestVersion\x12\x1a\n" +
	"\bbreaking\x18\x05 \x01(\bR\bbreaking\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary*z\n" +
	"\x12ResolutionStrategy\x12#\n" +
	"\x1fRESOLUTION_STRATEGY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aRESOLUTION_STRATEGY_NEWEST\x10\x01\x12\x1f\n" +
	"\x1bRESOLUTION_STRATEGY_MINIMAL\x10\x022\xe1\x02\n" +
	"\x0fManifestService\x12e\n" +
	"\vGetManifest\x12'.wippy.hub.module.v1.GetManifestRequest\x1a(.wippy.hub.module.v1.GetManifestResponse\"\x03\x90\x02\x01\x12}\n" +
	"\x13ResolveDependencies\x12/.wippy.hub.module.v1.ResolveDependenciesRequest\x1a0.wippy.hub.module.v1.ResolveDependenciesResponse\"\x03\x90\x02\x01\x12h\n" +
	"\fCheckUpdates\x12(.wippy.hub.module.v1.CheckUpdatesRequest\x1a).wippy.hub.module.v1.CheckUpdatesResponse\"\x03\x90\x02\x01B;Z9github.com/wippyai/proto-api/wippy/hub/module/v1;modulev1b\x06proto3"

var (
	file_wippy_hub_module_v1_manifest_service_proto_rawDescOnce sync.Once
	file_wippy_hub_module_v1_manifest_service_proto_rawDescData []byte
)

func file_wippy_hub_module_v1_manifest_service_proto_rawDescGZIP() []byte {
	file_wippy_hub_module_v1_manifest_service_proto_rawDescOnce.Do(func() {
		file_wippy_hub_module_v1_manifest_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_hub_module_v1_manifest_service_proto_rawDesc), len(file_wippy_hub_module_v1_manifest_service_proto_rawDesc)))
	})
	return file_wippy_hub_module_v1_manifest_service_proto_rawDescData
}

var file_wippy_hub_module_v1_manifest_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wippy_hub_module_v1_manifest_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_wippy_hub_module_v1_manifest_service_proto_goTypes = []any{
	(ResolutionStrategy)(0),             // 0: wippy.hub.module.v1.ResolutionStrategy
	(*GetManifestRequest)(nil),          // 1: wippy.hub.module.v1.GetManifestRequest
	(*GetManifestResponse)(nil),         // 2: wippy.hub.module.v1.GetManifestResponse
	(*ModuleManifest)(nil),              // 3: wippy.hub.module.v1.ModuleManifest
	(*ModuleInfo)(nil),                  // 4: wippy.hub.module.v1.ModuleInfo
	(*VersionInfo)(nil),                 // 5: wippy.hub.module.v1.VersionInfo
	(*ResolvedDependency)(nil),          // 6: wippy.hub.module.v1.ResolvedDependency
	(*DownloadInfo)(nil),                // 7: wippy.hub.module.v1.DownloadInfo
	(*ResolveDependenciesRequest)(nil),  // 8: wippy.hub.module.v1.ResolveDependenciesRequest
	(*DependencySpec)(nil),              // 9: wippy.hub.module.v1.DependencySpec
	(*InstalledModule)(nil),             // 10: wippy.hub.module.v1.InstalledModule
	(*ResolveDependenciesResponse)(nil), // 11: wippy.hub.module.v1.ResolveDependenciesResponse
	(*ResolvedModule)(nil),              // 12: wippy.hub.module.v1.ResolvedModule
	(*ResolutionError)(nil),             // 13: wippy.hub.module.v1.ResolutionError
	(*CheckUpdatesRequest)(nil),         // 14: wippy.hub.module.v1.CheckUpdatesRequest
	(*CheckUpdatesResponse)(nil),        // 15: wippy.hub.module.v1.CheckUpdatesResponse
	(*ModuleUpdate)(nil),                // 16: wippy.hub.module.v1.ModuleUpdate
	(*ModuleName)(nil),                  // 17: wippy.hub.module.v1.ModuleName
	(*VersionRef)(nil),                  // 18: wippy.hub.module.v1.VersionRef
	(*timestamppb.Timestamp)(nil),       // 19: google.protobuf.Timestamp
	(*VersionMetadata)(nil),             // 20: wippy.hub.module.v1.VersionMetadata
}
var file_wippy_hub_module_v1_manifest_service_proto_depIdxs = []int32{
	17, // 0: wippy.hub.module.v1.GetManifestRequest.module_name:type_name -> wippy.hub.module.v1.ModuleName
	18, // 1: wippy.hub.module.v1.GetManifestRequest.version:type_name -> wippy.hub.module.v1.VersionRef
	3,  // 2: wippy.hub.module.v1.GetManifestResponse.manifest:type_name -> wippy.hub.module.v1.ModuleManifest
	4,  // 3: wippy.hub.module.v1.ModuleManifest.module:type_name -> wippy.hub.module.v1.ModuleInfo
	5,  // 4: wippy.hub.module.v1.ModuleManifest.version:type_name -> wippy.hub.module.v1.VersionInfo
	6,  // 5: wippy.hub.module.v1.ModuleManifest.dependencies:type_name -> wippy.hub.module.v1.ResolvedDependency
	7,  // 6: wippy.hub.module.v1.ModuleManifest.download:type_name -> wippy.hub.module.v1.DownloadInfo
	19, // 7: wippy.hub.module.v1.VersionInfo.create_time:type_name -> google.protobuf.Timestamp
	20, // 8: wippy.hub.module.v1.VersionInfo.metadata:type_name -> wippy.hub.module.v1.VersionMetadata
	19, // 9: wippy.hub.module.v1.ResolvedDependency.download_expires_at:type_name -> google.protobuf.Timestamp
	19, // 10: wippy.hub.module.v1.DownloadInfo.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 11: wippy.hub.module.v1.ResolveDependenciesRequest.roots:type_name -> wippy.hub.module.v1.DependencySpec
	10, // 12: wippy.hub.module.v1.ResolveDependenciesRequest.installed:type_name -> wippy.hub.module.v1.InstalledModule
	0,  // 13: wippy.hub.module.v1.ResolveDependenciesRequest.strategy:type_name -> wippy.hub.module.v1.ResolutionStrategy
	12, // 14: wippy.hub.module.v1.ResolveDependenciesResponse.modules:type_name -> wippy.hub.module.v1.ResolvedModule
	13, // 15: wippy.hub.module.v1.ResolveDependenciesResponse.errors:type_name -> wippy.hub.module.v1.ResolutionError
	19, // 16: wippy.hub.module.v1.ResolvedModule.download_expires_at:type_name -> google.protobuf.Timestamp
	9,  // 17: wippy.hub.module.v1.ResolvedModule.dependencies:type_name -> wippy.hub.module.v1.DependencySpec
	10, // 18: wippy.hub.module.v1.CheckUpdatesRequest.installed:type_name -> wippy.hub.module.v1.InstalledModule
	16, // 19: wippy.hub.module.v1.CheckUpdatesResponse.updates:type_name -> wippy.hub.module.v1.ModuleUpdate
	1,  // 20: wippy.hub.module.v1.ManifestService.GetManifest:input_type -> wippy.hub.module.v1.GetManifestRequest
	8,  // 21: wippy.hub.module.v1.ManifestService.ResolveDependencies:input_type -> wippy.hub.module.v1.ResolveDependenciesRequest
	14, // 22: wippy.hub.module.v1.ManifestService.CheckUpdates:input_type -> wippy.hub.module.v1.CheckUpdatesRequest
	2,  // 23: wippy.hub.module.v1.ManifestService.GetManifest:output_type -> wippy.hub.module.v1.GetManifestResponse
	11, // 24: wippy.hub.module.v1.ManifestService.ResolveDependencies:output_type -> wippy.hub.module.v1.ResolveDependenciesResponse
	15, // 25: wippy.hub.module.v1.ManifestService.CheckUpdates:output_type -> wippy.hub.module.v1.CheckUpdatesResponse
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_wippy_hub_module_v1_manifest_service_proto_init() }
func file_wippy_hub_module_v1_manifest_service_proto_init() {
	if File_wippy_hub_module_v1_manifest_service_proto != nil {
		return
	}
	file_wippy_hub_module_v1_version_proto_init()
	file_wippy_hub_module_v1_publish_service_proto_init()
	file_wippy_hub_module_v1_manifest_service_proto_msgTypes[0].OneofWrappers = []any{
		(*GetManifestRequest_ModuleId)(nil),
		(*GetManifestRequest_ModuleName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_hub_module_v1_manifest_service_proto_rawDesc), len(file_wippy_hub_module_v1_manifest_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_hub_module_v1_manifest_service_proto_goTypes,
		DependencyIndexes: file_wippy_hub_module_v1_manifest_service_proto_depIdxs,
		EnumInfos:         file_wippy_hub_module_v1_manifest_service_proto_enumTypes,
		MessageInfos:      file_wippy_hub_module_v1_manifest_service_proto_msgTypes,
	}.Build()
	File_wippy_hub_module_v1_manifest_service_proto = out.File
	file_wippy_hub_module_v1_manifest_service_proto_goTypes = nil
	file_wippy_hub_module_v1_manifest_service_proto_depIdxs = nil
}
