// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/hub/module/v1/module_service.proto

package modulev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sort order for modules.
type ModuleSortOrder int32

const (
	ModuleSortOrder_MODULE_SORT_ORDER_UNSPECIFIED    ModuleSortOrder = 0
	ModuleSortOrder_MODULE_SORT_ORDER_NAME_ASC       ModuleSortOrder = 1
	ModuleSortOrder_MODULE_SORT_ORDER_NAME_DESC      ModuleSortOrder = 2
	ModuleSortOrder_MODULE_SORT_ORDER_CREATED_DESC   ModuleSortOrder = 3
	ModuleSortOrder_MODULE_SORT_ORDER_UPDATED_DESC   ModuleSortOrder = 4
	ModuleSortOrder_MODULE_SORT_ORDER_DOWNLOADS_DESC ModuleSortOrder = 5
)

// Enum value maps for ModuleSortOrder.
var (
	ModuleSortOrder_name = map[int32]string{
		0: "MODULE_SORT_ORDER_UNSPECIFIED",
		1: "MODULE_SORT_ORDER_NAME_ASC",
		2: "MODULE_SORT_ORDER_NAME_DESC",
		3: "MODULE_SORT_ORDER_CREATED_DESC",
		4: "MODULE_SORT_ORDER_UPDATED_DESC",
		5: "MODULE_SORT_ORDER_DOWNLOADS_DESC",
	}
	ModuleSortOrder_value = map[string]int32{
		"MODULE_SORT_ORDER_UNSPECIFIED":    0,
		"MODULE_SORT_ORDER_NAME_ASC":       1,
		"MODULE_SORT_ORDER_NAME_DESC":      2,
		"MODULE_SORT_ORDER_CREATED_DESC":   3,
		"MODULE_SORT_ORDER_UPDATED_DESC":   4,
		"MODULE_SORT_ORDER_DOWNLOADS_DESC": 5,
	}
)

func (x ModuleSortOrder) Enum() *ModuleSortOrder {
	p := new(ModuleSortOrder)
	*p = x
	return p
}

func (x ModuleSortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleSortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_wippy_hub_module_v1_module_service_proto_enumTypes[0].Descriptor()
}

func (ModuleSortOrder) Type() protoreflect.EnumType {
	return &file_wippy_hub_module_v1_module_service_proto_enumTypes[0]
}

func (x ModuleSortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleSortOrder.Descriptor instead.
func (ModuleSortOrder) EnumDescriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{0}
}

// Request to create a module.
type CreateModuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization ID.
	OrganizationId string `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Module name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Module description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Visibility.
	Visibility Visibility `protobuf:"varint,4,opt,name=visibility,proto3,enum=wippy.hub.module.v1.Visibility" json:"visibility,omitempty"`
	// Module type.
	Type          ModuleType `protobuf:"varint,5,opt,name=type,proto3,enum=wippy.hub.module.v1.ModuleType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModuleRequest) Reset() {
	*x = CreateModuleRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModuleRequest) ProtoMessage() {}

func (x *CreateModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModuleRequest.ProtoReflect.Descriptor instead.
func (*CreateModuleRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateModuleRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateModuleRequest) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *CreateModuleRequest) GetType() ModuleType {
	if x != nil {
		return x.Type
	}
	return ModuleType_MODULE_TYPE_UNSPECIFIED
}

// Response for create module.
type CreateModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModuleResponse) Reset() {
	*x = CreateModuleResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModuleResponse) ProtoMessage() {}

func (x *CreateModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModuleResponse.ProtoReflect.Descriptor instead.
func (*CreateModuleResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateModuleResponse) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

// Request to get a module.
type GetModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ModuleRef             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleRequest) Reset() {
	*x = GetModuleRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleRequest) ProtoMessage() {}

func (x *GetModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleRequest.ProtoReflect.Descriptor instead.
func (*GetModuleRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetModuleRequest) GetModule() *ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

// Response for get module.
type GetModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleResponse) Reset() {
	*x = GetModuleResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleResponse) ProtoMessage() {}

func (x *GetModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleResponse.ProtoReflect.Descriptor instead.
func (*GetModuleResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetModuleResponse) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

// Request to list modules.
type ListModulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by organization.
	OrganizationId string `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Page number (1-based).
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Items per page.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Filter by visibility.
	Visibility Visibility `protobuf:"varint,4,opt,name=visibility,proto3,enum=wippy.hub.module.v1.Visibility" json:"visibility,omitempty"`
	// Filter by type.
	Type ModuleType `protobuf:"varint,5,opt,name=type,proto3,enum=wippy.hub.module.v1.ModuleType" json:"type,omitempty"`
	// Sort order.
	SortOrder     ModuleSortOrder `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3,enum=wippy.hub.module.v1.ModuleSortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesRequest) Reset() {
	*x = ListModulesRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesRequest) ProtoMessage() {}

func (x *ListModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesRequest.ProtoReflect.Descriptor instead.
func (*ListModulesRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListModulesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListModulesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModulesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListModulesRequest) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *ListModulesRequest) GetType() ModuleType {
	if x != nil {
		return x.Type
	}
	return ModuleType_MODULE_TYPE_UNSPECIFIED
}

func (x *ListModulesRequest) GetSortOrder() ModuleSortOrder {
	if x != nil {
		return x.SortOrder
	}
	return ModuleSortOrder_MODULE_SORT_ORDER_UNSPECIFIED
}

// Response for list modules.
type ListModulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*Module              `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesResponse) Reset() {
	*x = ListModulesResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesResponse) ProtoMessage() {}

func (x *ListModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesResponse.ProtoReflect.Descriptor instead.
func (*ListModulesResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListModulesResponse) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *ListModulesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListModulesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModulesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Request to update a module.
type UpdateModuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module to update.
	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	// New description (optional).
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// New visibility (optional).
	Visibility    *Visibility `protobuf:"varint,3,opt,name=visibility,proto3,enum=wippy.hub.module.v1.Visibility,oneof" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModuleRequest) Reset() {
	*x = UpdateModuleRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModuleRequest) ProtoMessage() {}

func (x *UpdateModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateModuleRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateModuleRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *UpdateModuleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateModuleRequest) GetVisibility() Visibility {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

// Response for update module.
type UpdateModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModuleResponse) Reset() {
	*x = UpdateModuleResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModuleResponse) ProtoMessage() {}

func (x *UpdateModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModuleResponse.ProtoReflect.Descriptor instead.
func (*UpdateModuleResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateModuleResponse) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

// Request to delete a module.
type DeleteModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModuleRequest) Reset() {
	*x = DeleteModuleRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModuleRequest) ProtoMessage() {}

func (x *DeleteModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteModuleRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteModuleRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

// Response for delete module.
type DeleteModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModuleResponse) Reset() {
	*x = DeleteModuleResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModuleResponse) ProtoMessage() {}

func (x *DeleteModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteModuleResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{9}
}

// Request to deprecate a module.
type DeprecateModuleRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ModuleId string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Message  string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Alternative module to recommend.
	Alternative   *ModuleRef `protobuf:"bytes,3,opt,name=alternative,proto3" json:"alternative,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeprecateModuleRequest) Reset() {
	*x = DeprecateModuleRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprecateModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprecateModuleRequest) ProtoMessage() {}

func (x *DeprecateModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprecateModuleRequest.ProtoReflect.Descriptor instead.
func (*DeprecateModuleRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeprecateModuleRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *DeprecateModuleRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeprecateModuleRequest) GetAlternative() *ModuleRef {
	if x != nil {
		return x.Alternative
	}
	return nil
}

// Response for deprecate module.
type DeprecateModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeprecateModuleResponse) Reset() {
	*x = DeprecateModuleResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprecateModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprecateModuleResponse) ProtoMessage() {}

func (x *DeprecateModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprecateModuleResponse.ProtoReflect.Descriptor instead.
func (*DeprecateModuleResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeprecateModuleResponse) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

// Request to search modules.
type SearchModulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search query.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Page number.
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Items per page.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Filter by keywords.
	Keywords []string `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords,omitempty"`
	// Filter by license.
	License string `protobuf:"bytes,5,opt,name=license,proto3" json:"license,omitempty"`
	// Include deprecated.
	IncludeDeprecated bool `protobuf:"varint,6,opt,name=include_deprecated,json=includeDeprecated,proto3" json:"include_deprecated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchModulesRequest) Reset() {
	*x = SearchModulesRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchModulesRequest) ProtoMessage() {}

func (x *SearchModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchModulesRequest.ProtoReflect.Descriptor instead.
func (*SearchModulesRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{12}
}

func (x *SearchModulesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchModulesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchModulesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchModulesRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *SearchModulesRequest) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *SearchModulesRequest) GetIncludeDeprecated() bool {
	if x != nil {
		return x.IncludeDeprecated
	}
	return false
}

// Response for search modules.
type SearchModulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*Module              `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchModulesResponse) Reset() {
	*x = SearchModulesResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchModulesResponse) ProtoMessage() {}

func (x *SearchModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchModulesResponse.ProtoReflect.Descriptor instead.
func (*SearchModulesResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{13}
}

func (x *SearchModulesResponse) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *SearchModulesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchModulesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchModulesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Request to list versions.
type ListVersionsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Module   *ModuleRef             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Page     int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Include yanked versions.
	IncludeYanked bool `protobuf:"varint,4,opt,name=include_yanked,json=includeYanked,proto3" json:"include_yanked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListVersionsRequest) GetModule() *ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *ListVersionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVersionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVersionsRequest) GetIncludeYanked() bool {
	if x != nil {
		return x.IncludeYanked
	}
	return false
}

// Response for list versions.
type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*Version             `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListVersionsResponse) GetVersions() []*Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListVersionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListVersionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVersionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Request to get a version.
type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ModuleRef             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Version       *VersionRef            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetVersionRequest) GetModule() *ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *GetVersionRequest) GetVersion() *VersionRef {
	if x != nil {
		return x.Version
	}
	return nil
}

// Response for get version.
type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetVersionResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

// Request to list version files.
type ListVersionFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ModuleRef             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Version       *VersionRef            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionFilesRequest) Reset() {
	*x = ListVersionFilesRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionFilesRequest) ProtoMessage() {}

func (x *ListVersionFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionFilesRequest.ProtoReflect.Descriptor instead.
func (*ListVersionFilesRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{18}
}

func (x *ListVersionFilesRequest) GetModule() *ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *ListVersionFilesRequest) GetVersion() *VersionRef {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ListVersionFilesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVersionFilesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Response for list version files.
type ListVersionFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*VersionFile         `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionFilesResponse) Reset() {
	*x = ListVersionFilesResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionFilesResponse) ProtoMessage() {}

func (x *ListVersionFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionFilesResponse.ProtoReflect.Descriptor instead.
func (*ListVersionFilesResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListVersionFilesResponse) GetFiles() []*VersionFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListVersionFilesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListVersionFilesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVersionFilesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Request to get dependencies.
type GetDependenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ModuleRef             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Version       *VersionRef            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependenciesRequest) Reset() {
	*x = GetDependenciesRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependenciesRequest) ProtoMessage() {}

func (x *GetDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependenciesRequest.ProtoReflect.Descriptor instead.
func (*GetDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetDependenciesRequest) GetModule() *ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *GetDependenciesRequest) GetVersion() *VersionRef {
	if x != nil {
		return x.Version
	}
	return nil
}

// Response for get dependencies.
type GetDependenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dependencies  []*Dependency          `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependenciesResponse) Reset() {
	*x = GetDependenciesResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependenciesResponse) ProtoMessage() {}

func (x *GetDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependenciesResponse.ProtoReflect.Descriptor instead.
func (*GetDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetDependenciesResponse) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

// Request to get dependents.
type GetDependentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *ModuleRef             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependentsRequest) Reset() {
	*x = GetDependentsRequest{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependentsRequest) ProtoMessage() {}

func (x *GetDependentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependentsRequest.ProtoReflect.Descriptor instead.
func (*GetDependentsRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetDependentsRequest) GetModule() *ModuleRef {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *GetDependentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDependentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Response for get dependents.
type GetDependentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Modules that depend on this one.
	Dependents    []*DependentModule `protobuf:"bytes,1,rep,name=dependents,proto3" json:"dependents,omitempty"`
	Total         int32              `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32              `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32              `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependentsResponse) Reset() {
	*x = GetDependentsResponse{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependentsResponse) ProtoMessage() {}

func (x *GetDependentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependentsResponse.ProtoReflect.Descriptor instead.
func (*GetDependentsResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetDependentsResponse) GetDependents() []*DependentModule {
	if x != nil {
		return x.Dependents
	}
	return nil
}

func (x *GetDependentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetDependentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDependentsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Module that depends on another.
type DependentModule struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Org     string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Version constraint used.
	Constraint    string `protobuf:"bytes,4,opt,name=constraint,proto3" json:"constraint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependentModule) Reset() {
	*x = DependentModule{}
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependentModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependentModule) ProtoMessage() {}

func (x *DependentModule) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_module_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependentModule.ProtoReflect.Descriptor instead.
func (*DependentModule) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_module_service_proto_rawDescGZIP(), []int{24}
}

func (x *DependentModule) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *DependentModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DependentModule) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DependentModule) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

var File_wippy_hub_module_v1_module_service_proto protoreflect.FileDescriptor

const file_wippy_hub_module_v1_module_service_proto_rawDesc = "" +
	"\n" +
	"(wippy/hub/module/v1/module_service.proto\x12\x13wippy.hub.module.v1\x1a\x1bbuf/validate/validate.proto\x1a wippy/hub/module/v1/module.proto\x1a!wippy/hub/module/v1/version.proto\"\x92\x02\n" +
	"\x13CreateModuleRequest\x121\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eorganizationId\x120\n" +
	"\x04name\x18\x02 \x01(\tB\x1c\xbaH\x19r\x17\x10\x01\x18@2\x11^[a-z][a-z0-9-]*$R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12?\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x1f.wippy.hub.module.v1.VisibilityR\n" +
	"visibility\x123\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1f.wippy.hub.module.v1.ModuleTypeR\x04type\"K\n" +
	"\x14CreateModuleResponse\x123\n" +
	"\x06module\x18\x01 \x01(\v2\x1b.wippy.hub.module.v1.ModuleR\x06module\"R\n" +
	"\x10GetModuleRequest\x12>\n" +
	"\x06module\x18\x01 \x01(\v2\x1e.wippy.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\"H\n" +
	"\x11GetModuleResponse\x123\n" +
	"\x06module\x18\x01 \x01(\v2\x1b.wippy.hub.module.v1.ModuleR\x06module\"\xa9\x02\n" +
	"\x12ListModulesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12?\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x1f.wippy.hub.module.v1.VisibilityR\n" +
	"visibility\x123\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1f.wippy.hub.module.v1.ModuleTypeR\x04type\x12C\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x0e2$.wippy.hub.module.v1.ModuleSortOrderR\tsortOrder\"\x93\x01\n" +
	"\x13ListModulesResponse\x125\n" +
	"\amodules\x18\x01 \x03(\v2\x1b.wippy.hub.module.v1.ModuleR\amodules\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xc8\x01\n" +
	"\x13UpdateModuleRequest\x12%\n" +
	"\tmodule_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bmoduleId\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12D\n" +
	"\n" +
	"visibility\x18\x03 \x01(\x0e2\x1f.wippy.hub.module.v1.VisibilityH\x01R\n" +
	"visibility\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_visibility\"K\n" +
	"\x14UpdateModuleResponse\x123\n" +
	"\x06module\x18\x01 \x01(\v2\x1b.wippy.hub.module.v1.ModuleR\x06module\"<\n" +
	"\x13DeleteModuleRequest\x12%\n" +
	"\tmodule_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bmoduleId\"\x16\n" +
	"\x14DeleteModuleResponse\"\x9b\x01\n" +
	"\x16DeprecateModuleRequest\x12%\n" +
	"\tmodule_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bmoduleId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\valternative\x18\x03 \x01(\v2\x1e.wippy.hub.module.v1.ModuleRefR\valternative\"N\n" +
	"\x17DeprecateModuleResponse\x123\n" +
	"\x06module\x18\x01 \x01(\v2\x1b.wippy.hub.module.v1.ModuleR\x06module\"\xce\x01\n" +
	"\x14SearchModulesRequest\x12 \n" +
	"\x05query\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc8\x01R\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1a\n" +
	"\bkeywords\x18\x04 \x03(\tR\bkeywords\x12\x18\n" +
	"\alicense\x18\x05 \x01(\tR\alicense\x12-\n" +
	"\x12include_deprecated\x18\x06 \x01(\bR\x11includeDeprecated\"\x95\x01\n" +
	"\x15SearchModulesResponse\x125\n" +
	"\amodules\x18\x01 \x03(\v2\x1b.wippy.hub.module.v1.ModuleR\amodules\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xad\x01\n" +
	"\x13ListVersionsRequest\x12>\n" +
	"\x06module\x18\x01 \x01(\v2\x1e.wippy.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12%\n" +
	"\x0einclude_yanked\x18\x04 \x01(\bR\rincludeYanked\"\x97\x01\n" +
	"\x14ListVersionsResponse\x128\n" +
	"\bversions\x18\x01 \x03(\v2\x1c.wippy.hub.module.v1.VersionR\bversions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x96\x01\n" +
	"\x11GetVersionRequest\x12>\n" +
	"\x06module\x18\x01 \x01(\v2\x1e.wippy.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x12A\n" +
	"\aversion\x18\x02 \x01(\v2\x1f.wippy.hub.module.v1.VersionRefB\x06\xbaH\x03\xc8\x01\x01R\aversion\"L\n" +
	"\x12GetVersionResponse\x126\n" +
	"\aversion\x18\x01 \x01(\v2\x1c.wippy.hub.module.v1.VersionR\aversion\"\xcd\x01\n" +
	"\x17ListVersionFilesRequest\x12>\n" +
	"\x06module\x18\x01 \x01(\v2\x1e.wippy.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x12A\n" +
	"\aversion\x18\x02 \x01(\v2\x1f.wippy.hub.module.v1.VersionRefB\x06\xbaH\x03\xc8\x01\x01R\aversion\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x99\x01\n" +
	"\x18ListVersionFilesResponse\x126\n" +
	"\x05files\x18\x01 \x03(\v2 .wippy.hub.module.v1.VersionFileR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x93\x01\n" +
	"\x16GetDependenciesRequest\x12>\n" +
	"\x06module\x18\x01 \x01(\v2\x1e.wippy.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x129\n" +
	"\aversion\x18\x02 \x01(\v2\x1f.wippy.hub.module.v1.VersionRefR\aversion\"^\n" +
	"\x17GetDependenciesResponse\x12C\n" +
	"\fdependencies\x18\x01 \x03(\v2\x1f.wippy.hub.module.v1.DependencyR\fdependencies\"\x87\x01\n" +
	"\x14GetDependentsRequest\x12>\n" +
	"\x06module\x18\x01 \x01(\v2\x1e.wippy.hub.module.v1.ModuleRefB\x06\xbaH\x03\xc8\x01\x01R\x06module\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa4\x01\n" +
	"\x15GetDependentsResponse\x12D\n" +
	"\n" +
	"dependents\x18\x01 \x03(\v2$.wippy.hub.module.v1.DependentModuleR\n" +
	"dependents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"q\n" +
	"\x0fDependentModule\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"constraint\x18\x04 \x01(\tR\n" +
	"constraint*\xe3\x01\n" +
	"\x0fModuleSortOrder\x12!\n" +
	"\x1dMODULE_SORT_ORDER_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aMODULE_SORT_ORDER_NAME_ASC\x10\x01\x12\x1f\n" +
	"\x1bMODULE_SORT_ORDER_NAME_DESC\x10\x02\x12\"\n" +
	"\x1eMODULE_SORT_ORDER_CREATED_DESC\x10\x03\x12\"\n" +
	"\x1eMODULE_SORT_ORDER_UPDATED_DESC\x10\x04\x12$\n" +
	" MODULE_SORT_ORDER_DOWNLOADS_DESC\x10\x052\x8d\n" +
	"\n" +
	"\rModuleService\x12e\n" +
	"\fCreateModule\x12(.wippy.hub.module.v1.CreateModuleRequest\x1a).wippy.hub.module.v1.CreateModuleResponse\"\x00\x12_\n" +
	"\tGetModule\x12%.wippy.hub.module.v1.GetModuleRequest\x1a&.wippy.hub.module.v1.GetModuleResponse\"\x03\x90\x02\x01\x12e\n" +
	"\vListModules\x12'.wippy.hub.module.v1.ListModulesRequest\x1a(.wippy.hub.module.v1.ListModulesResponse\"\x03\x90\x02\x01\x12e\n" +
	"\fUpdateModule\x12(.wippy.hub.module.v1.UpdateModuleRequest\x1a).wippy.hub.module.v1.UpdateModuleResponse\"\x00\x12e\n" +
	"\fDeleteModule\x12(.wippy.hub.module.v1.DeleteModuleRequest\x1a).wippy.hub.module.v1.DeleteModuleResponse\"\x00\x12n\n" +
	"\x0fDeprecateModule\x12+.wippy.hub.module.v1.DeprecateModuleRequest\x1a,.wippy.hub.module.v1.DeprecateModuleResponse\"\x00\x12k\n" +
	"\rSearchModules\x12).wippy.hub.module.v1.SearchModulesRequest\x1a*.wippy.hub.module.v1.SearchModulesResponse\"\x03\x90\x02\x01\x12h\n" +
	"\fListVersions\x12(.wippy.hub.module.v1.ListVersionsRequest\x1a).wippy.hub.module.v1.ListVersionsResponse\"\x03\x90\x02\x01\x12b\n" +
	"\n" +
	"GetVersion\x12&.wippy.hub.module.v1.GetVersionRequest\x1a'.wippy.hub.module.v1.GetVersionResponse\"\x03\x90\x02\x01\x12t\n" +
	"\x10ListVersionFiles\x12,.wippy.hub.module.v1.ListVersionFilesRequest\x1a-.wippy.hub.module.v1.ListVersionFilesResponse\"\x03\x90\x02\x01\x12q\n" +
	"\x0fGetDependencies\x12+.wippy.hub.module.v1.GetDependenciesRequest\x1a,.wippy.hub.module.v1.GetDependenciesResponse\"\x03\x90\x02\x01\x12k\n" +
	"\rGetDependents\x12).wippy.hub.module.v1.GetDependentsRequest\x1a*.wippy.hub.module.v1.GetDependentsResponse\"\x03\x90\x02\x01B;Z9github.com/wippyai/proto-api/wippy/hub/module/v1;modulev1b\x06proto3"

var (
	file_wippy_hub_module_v1_module_service_proto_rawDescOnce sync.Once
	file_wippy_hub_module_v1_module_service_proto_rawDescData []byte
)

func file_wippy_hub_module_v1_module_service_proto_rawDescGZIP() []byte {
	file_wippy_hub_module_v1_module_service_proto_rawDescOnce.Do(func() {
		file_wippy_hub_module_v1_module_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_hub_module_v1_module_service_proto_rawDesc), len(file_wippy_hub_module_v1_module_service_proto_rawDesc)))
	})
	return file_wippy_hub_module_v1_module_service_proto_rawDescData
}

var file_wippy_hub_module_v1_module_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wippy_hub_module_v1_module_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_wippy_hub_module_v1_module_service_proto_goTypes = []any{
	(ModuleSortOrder)(0),             // 0: wippy.hub.module.v1.ModuleSortOrder
	(*CreateModuleRequest)(nil),      // 1: wippy.hub.module.v1.CreateModuleRequest
	(*CreateModuleResponse)(nil),     // 2: wippy.hub.module.v1.CreateModuleResponse
	(*GetModuleRequest)(nil),         // 3: wippy.hub.module.v1.GetModuleRequest
	(*GetModuleResponse)(nil),        // 4: wippy.hub.module.v1.GetModuleResponse
	(*ListModulesRequest)(nil),       // 5: wippy.hub.module.v1.ListModulesRequest
	(*ListModulesResponse)(nil),      // 6: wippy.hub.module.v1.ListModulesResponse
	(*UpdateModuleRequest)(nil),      // 7: wippy.hub.module.v1.UpdateModuleRequest
	(*UpdateModuleResponse)(nil),     // 8: wippy.hub.module.v1.UpdateModuleResponse
	(*DeleteModuleRequest)(nil),      // 9: wippy.hub.module.v1.DeleteModuleRequest
	(*DeleteModuleResponse)(nil),     // 10: wippy.hub.module.v1.DeleteModuleResponse
	(*DeprecateModuleRequest)(nil),   // 11: wippy.hub.module.v1.DeprecateModuleRequest
	(*DeprecateModuleResponse)(nil),  // 12: wippy.hub.module.v1.DeprecateModuleResponse
	(*SearchModulesRequest)(nil),     // 13: wippy.hub.module.v1.SearchModulesRequest
	(*SearchModulesResponse)(nil),    // 14: wippy.hub.module.v1.SearchModulesResponse
	(*ListVersionsRequest)(nil),      // 15: wippy.hub.module.v1.ListVersionsRequest
	(*ListVersionsResponse)(nil),     // 16: wippy.hub.module.v1.ListVersionsResponse
	(*GetVersionRequest)(nil),        // 17: wippy.hub.module.v1.GetVersionRequest
	(*GetVersionResponse)(nil),       // 18: wippy.hub.module.v1.GetVersionResponse
	(*ListVersionFilesRequest)(nil),  // 19: wippy.hub.module.v1.ListVersionFilesRequest
	(*ListVersionFilesResponse)(nil), // 20: wippy.hub.module.v1.ListVersionFilesResponse
	(*GetDependenciesRequest)(nil),   // 21: wippy.hub.module.v1.GetDependenciesRequest
	(*GetDependenciesResponse)(nil),  // 22: wippy.hub.module.v1.GetDependenciesResponse
	(*GetDependentsRequest)(nil),     // 23: wippy.hub.module.v1.GetDependentsRequest
	(*GetDependentsResponse)(nil),    // 24: wippy.hub.module.v1.GetDependentsResponse
	(*DependentModule)(nil),          // 25: wippy.hub.module.v1.DependentModule
	(Visibility)(0),                  // 26: wippy.hub.module.v1.Visibility
	(ModuleType)(0),                  // 27: wippy.hub.module.v1.ModuleType
	(*Module)(nil),                   // 28: wippy.hub.module.v1.Module
	(*ModuleRef)(nil),                // 29: wippy.hub.module.v1.ModuleRef
	(*Version)(nil),                  // 30: wippy.hub.module.v1.Version
	(*VersionRef)(nil),               // 31: wippy.hub.module.v1.VersionRef
	(*VersionFile)(nil),              // 32: wippy.hub.module.v1.VersionFile
	(*Dependency)(nil),               // 33: wippy.hub.module.v1.Dependency
}
var file_wippy_hub_module_v1_module_service_proto_depIdxs = []int32{
	26, // 0: wippy.hub.module.v1.CreateModuleRequest.visibility:type_name -> wippy.hub.module.v1.Visibility
	27, // 1: wippy.hub.module.v1.CreateModuleRequest.type:type_name -> wippy.hub.module.v1.ModuleType
	28, // 2: wippy.hub.module.v1.CreateModuleResponse.module:type_name -> wippy.hub.module.v1.Module
	29, // 3: wippy.hub.module.v1.GetModuleRequest.module:type_name -> wippy.hub.module.v1.ModuleRef
	28, // 4: wippy.hub.module.v1.GetModuleResponse.module:type_name -> wippy.hub.module.v1.Module
	26, // 5: wippy.hub.module.v1.ListModulesRequest.visibility:type_name -> wippy.hub.module.v1.Visibility
	27, // 6: wippy.hub.module.v1.ListModulesRequest.type:type_name -> wippy.hub.module.v1.ModuleType
	0,  // 7: wippy.hub.module.v1.ListModulesRequest.sort_order:type_name -> wippy.hub.module.v1.ModuleSortOrder
	28, // 8: wippy.hub.module.v1.ListModulesResponse.modules:type_name -> wippy.hub.module.v1.Module
	26, // 9: wippy.hub.module.v1.UpdateModuleRequest.visibility:type_name -> wippy.hub.module.v1.Visibility
	28, // 10: wippy.hub.module.v1.UpdateModuleResponse.module:type_name -> wippy.hub.module.v1.Module
	29, // 11: wippy.hub.module.v1.DeprecateModuleRequest.alternative:type_name -> wippy.hub.module.v1.ModuleRef
	28, // 12: wippy.hub.module.v1.DeprecateModuleResponse.module:type_name -> wippy.hub.module.v1.Module
	28, // 13: wippy.hub.module.v1.SearchModulesResponse.modules:type_name -> wippy.hub.module.v1.Module
	29, // 14: wippy.hub.module.v1.ListVersionsRequest.module:type_name -> wippy.hub.module.v1.ModuleRef
	30, // 15: wippy.hub.module.v1.ListVersionsResponse.versions:type_name -> wippy.hub.module.v1.Version
	29, // 16: wippy.hub.module.v1.GetVersionRequest.module:type_name -> wippy.hub.module.v1.ModuleRef
	31, // 17: wippy.hub.module.v1.GetVersionRequest.version:type_name -> wippy.hub.module.v1.VersionRef
	30, // 18: wippy.hub.module.v1.GetVersionResponse.version:type_name -> wippy.hub.module.v1.Version
	29, // 19: wippy.hub.module.v1.ListVersionFilesRequest.module:type_name -> wippy.hub.module.v1.ModuleRef
	31, // 20: wippy.hub.module.v1.ListVersionFilesRequest.version:type_name -> wippy.hub.module.v1.VersionRef
	32, // 21: wippy.hub.module.v1.ListVersionFilesResponse.files:type_name -> wippy.hub.module.v1.VersionFile
	29, // 22: wippy.hub.module.v1.GetDependenciesRequest.module:type_name -> wippy.hub.module.v1.ModuleRef
	31, // 23: wippy.hub.module.v1.GetDependenciesRequest.version:type_name -> wippy.hub.module.v1.VersionRef
	33, // 24: wippy.hub.module.v1.GetDependenciesResponse.dependencies:type_name -> wippy.hub.module.v1.Dependency
	29, // 25: wippy.hub.module.v1.GetDependentsRequest.module:type_name -> wippy.hub.module.v1.ModuleRef
	25, // 26: wippy.hub.module.v1.GetDependentsResponse.dependents:type_name -> wippy.hub.module.v1.DependentModule
	1,  // 27: wippy.hub.module.v1.ModuleService.CreateModule:input_type -> wippy.hub.module.v1.CreateModuleRequest
	3,  // 28: wippy.hub.module.v1.ModuleService.GetModule:input_type -> wippy.hub.module.v1.GetModuleRequest
	5,  // 29: wippy.hub.module.v1.ModuleService.ListModules:input_type -> wippy.hub.module.v1.ListModulesRequest
	7,  // 30: wippy.hub.module.v1.ModuleService.UpdateModule:input_type -> wippy.hub.module.v1.UpdateModuleRequest
	9,  // 31: wippy.hub.module.v1.ModuleService.DeleteModule:input_type -> wippy.hub.module.v1.DeleteModuleRequest
	11, // 32: wippy.hub.module.v1.ModuleService.DeprecateModule:input_type -> wippy.hub.module.v1.DeprecateModuleRequest
	13, // 33: wippy.hub.module.v1.ModuleService.SearchModules:input_type -> wippy.hub.module.v1.SearchModulesRequest
	15, // 34: wippy.hub.module.v1.ModuleService.ListVersions:input_type -> wippy.hub.module.v1.ListVersionsRequest
	17, // 35: wippy.hub.module.v1.ModuleService.GetVersion:input_type -> wippy.hub.module.v1.GetVersionRequest
	19, // 36: wippy.hub.module.v1.ModuleService.ListVersionFiles:input_type -> wippy.hub.module.v1.ListVersionFilesRequest
	21, // 37: wippy.hub.module.v1.ModuleService.GetDependencies:input_type -> wippy.hub.module.v1.GetDependenciesRequest
	23, // 38: wippy.hub.module.v1.ModuleService.GetDependents:input_type -> wippy.hub.module.v1.GetDependentsRequest
	2,  // 39: wippy.hub.module.v1.ModuleService.CreateModule:output_type -> wippy.hub.module.v1.CreateModuleResponse
	4,  // 40: wippy.hub.module.v1.ModuleService.GetModule:output_type -> wippy.hub.module.v1.GetModuleResponse
	6,  // 41: wippy.hub.module.v1.ModuleService.ListModules:output_type -> wippy.hub.module.v1.ListModulesResponse
	8,  // 42: wippy.hub.module.v1.ModuleService.UpdateModule:output_type -> wippy.hub.module.v1.UpdateModuleResponse
	10, // 43: wippy.hub.module.v1.ModuleService.DeleteModule:output_type -> wippy.hub.module.v1.DeleteModuleResponse
	12, // 44: wippy.hub.module.v1.ModuleService.DeprecateModule:output_type -> wippy.hub.module.v1.DeprecateModuleResponse
	14, // 45: wippy.hub.module.v1.ModuleService.SearchModules:output_type -> wippy.hub.module.v1.SearchModulesResponse
	16, // 46: wippy.hub.module.v1.ModuleService.ListVersions:output_type -> wippy.hub.module.v1.ListVersionsResponse
	18, // 47: wippy.hub.module.v1.ModuleService.GetVersion:output_type -> wippy.hub.module.v1.GetVersionResponse
	20, // 48: wippy.hub.module.v1.ModuleService.ListVersionFiles:output_type -> wippy.hub.module.v1.ListVersionFilesResponse
	22, // 49: wippy.hub.module.v1.ModuleService.GetDependencies:output_type -> wippy.hub.module.v1.GetDependenciesResponse
	24, // 50: wippy.hub.module.v1.ModuleService.GetDependents:output_type -> wippy.hub.module.v1.GetDependentsResponse
	39, // [39:51] is the sub-list for method output_type
	27, // [27:39] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_wippy_hub_module_v1_module_service_proto_init() }
func file_wippy_hub_module_v1_module_service_proto_init() {
	if File_wippy_hub_module_v1_module_service_proto != nil {
		return
	}
	file_wippy_hub_module_v1_module_proto_init()
	file_wippy_hub_module_v1_version_proto_init()
	file_wippy_hub_module_v1_module_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_hub_module_v1_module_service_proto_rawDesc), len(file_wippy_hub_module_v1_module_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_hub_module_v1_module_service_proto_goTypes,
		DependencyIndexes: file_wippy_hub_module_v1_module_service_proto_depIdxs,
		EnumInfos:         file_wippy_hub_module_v1_module_service_proto_enumTypes,
		MessageInfos:      file_wippy_hub_module_v1_module_service_proto_msgTypes,
	}.Build()
	File_wippy_hub_module_v1_module_service_proto = out.File
	file_wippy_hub_module_v1_module_service_proto_goTypes = nil
	file_wippy_hub_module_v1_module_service_proto_depIdxs = nil
}
