// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wippy/hub/module/v1/publish_service.proto

package modulev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of a publish operation.
type PublishStatus int32

const (
	PublishStatus_PUBLISH_STATUS_UNSPECIFIED PublishStatus = 0
	// Waiting for WAPP upload.
	PublishStatus_PUBLISH_STATUS_PENDING_UPLOAD PublishStatus = 1
	// Upload received, processing.
	PublishStatus_PUBLISH_STATUS_PROCESSING PublishStatus = 2
	// Validation in progress.
	PublishStatus_PUBLISH_STATUS_VALIDATING PublishStatus = 3
	// Successfully published.
	PublishStatus_PUBLISH_STATUS_COMPLETED PublishStatus = 4
	// Failed with error.
	PublishStatus_PUBLISH_STATUS_FAILED PublishStatus = 5
	// Cancelled by user.
	PublishStatus_PUBLISH_STATUS_CANCELLED PublishStatus = 6
)

// Enum value maps for PublishStatus.
var (
	PublishStatus_name = map[int32]string{
		0: "PUBLISH_STATUS_UNSPECIFIED",
		1: "PUBLISH_STATUS_PENDING_UPLOAD",
		2: "PUBLISH_STATUS_PROCESSING",
		3: "PUBLISH_STATUS_VALIDATING",
		4: "PUBLISH_STATUS_COMPLETED",
		5: "PUBLISH_STATUS_FAILED",
		6: "PUBLISH_STATUS_CANCELLED",
	}
	PublishStatus_value = map[string]int32{
		"PUBLISH_STATUS_UNSPECIFIED":    0,
		"PUBLISH_STATUS_PENDING_UPLOAD": 1,
		"PUBLISH_STATUS_PROCESSING":     2,
		"PUBLISH_STATUS_VALIDATING":     3,
		"PUBLISH_STATUS_COMPLETED":      4,
		"PUBLISH_STATUS_FAILED":         5,
		"PUBLISH_STATUS_CANCELLED":      6,
	}
)

func (x PublishStatus) Enum() *PublishStatus {
	p := new(PublishStatus)
	*p = x
	return p
}

func (x PublishStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wippy_hub_module_v1_publish_service_proto_enumTypes[0].Descriptor()
}

func (PublishStatus) Type() protoreflect.EnumType {
	return &file_wippy_hub_module_v1_publish_service_proto_enumTypes[0]
}

func (x PublishStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishStatus.Descriptor instead.
func (PublishStatus) EnumDescriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{0}
}

// Request to initiate a publish operation.
type InitiatePublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module to publish to (org/name format or module ID).
	//
	// Types that are valid to be assigned to Module:
	//
	//	*InitiatePublishRequest_ModuleId
	//	*InitiatePublishRequest_ModuleName
	Module isInitiatePublishRequest_Module `protobuf_oneof:"module"`
	// Version OR label - mutually exclusive.
	//
	// Types that are valid to be assigned to Target:
	//
	//	*InitiatePublishRequest_Version
	//	*InitiatePublishRequest_Label
	Target isInitiatePublishRequest_Target `protobuf_oneof:"target"`
	// Expected file size for validation.
	ExpectedSizeBytes uint64 `protobuf:"varint,4,opt,name=expected_size_bytes,json=expectedSizeBytes,proto3" json:"expected_size_bytes,omitempty"`
	// SHA-256 digest of the WAPP file for verification.
	Digest string `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	// Whether this is a protected module (bytecode).
	// Requires paid subscription.
	Protected bool `protobuf:"varint,6,opt,name=protected,proto3" json:"protected,omitempty"`
	// Release notes for this publish (optional).
	// For label publishes, if not provided, uses previous label release notes.
	ReleaseNotes  string `protobuf:"bytes,8,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatePublishRequest) Reset() {
	*x = InitiatePublishRequest{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePublishRequest) ProtoMessage() {}

func (x *InitiatePublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePublishRequest.ProtoReflect.Descriptor instead.
func (*InitiatePublishRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{0}
}

func (x *InitiatePublishRequest) GetModule() isInitiatePublishRequest_Module {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *InitiatePublishRequest) GetModuleId() string {
	if x != nil {
		if x, ok := x.Module.(*InitiatePublishRequest_ModuleId); ok {
			return x.ModuleId
		}
	}
	return ""
}

func (x *InitiatePublishRequest) GetModuleName() *ModuleName {
	if x != nil {
		if x, ok := x.Module.(*InitiatePublishRequest_ModuleName); ok {
			return x.ModuleName
		}
	}
	return nil
}

func (x *InitiatePublishRequest) GetTarget() isInitiatePublishRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *InitiatePublishRequest) GetVersion() string {
	if x != nil {
		if x, ok := x.Target.(*InitiatePublishRequest_Version); ok {
			return x.Version
		}
	}
	return ""
}

func (x *InitiatePublishRequest) GetLabel() string {
	if x != nil {
		if x, ok := x.Target.(*InitiatePublishRequest_Label); ok {
			return x.Label
		}
	}
	return ""
}

func (x *InitiatePublishRequest) GetExpectedSizeBytes() uint64 {
	if x != nil {
		return x.ExpectedSizeBytes
	}
	return 0
}

func (x *InitiatePublishRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *InitiatePublishRequest) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *InitiatePublishRequest) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

type isInitiatePublishRequest_Module interface {
	isInitiatePublishRequest_Module()
}

type InitiatePublishRequest_ModuleId struct {
	// Module ID.
	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3,oneof"`
}

type InitiatePublishRequest_ModuleName struct {
	// Module name in org/name format.
	ModuleName *ModuleName `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3,oneof"`
}

func (*InitiatePublishRequest_ModuleId) isInitiatePublishRequest_Module() {}

func (*InitiatePublishRequest_ModuleName) isInitiatePublishRequest_Module() {}

type isInitiatePublishRequest_Target interface {
	isInitiatePublishRequest_Target()
}

type InitiatePublishRequest_Version struct {
	// Semantic version to publish (immutable).
	Version string `protobuf:"bytes,3,opt,name=version,proto3,oneof"`
}

type InitiatePublishRequest_Label struct {
	// Label to publish to (mutable, e.g., "develop", "nightly").
	// Creates auto-versioned entry like 0.0.0-{label}.{timestamp}.
	Label string `protobuf:"bytes,7,opt,name=label,proto3,oneof"`
}

func (*InitiatePublishRequest_Version) isInitiatePublishRequest_Target() {}

func (*InitiatePublishRequest_Label) isInitiatePublishRequest_Target() {}

// Module name reference.
type ModuleName struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization name.
	Org string `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	// Module name.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleName) Reset() {
	*x = ModuleName{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleName) ProtoMessage() {}

func (x *ModuleName) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleName.ProtoReflect.Descriptor instead.
func (*ModuleName) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleName) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ModuleName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response to initiate publish.
type InitiatePublishResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for this publish operation.
	PublishId string `protobuf:"bytes,1,opt,name=publish_id,json=publishId,proto3" json:"publish_id,omitempty"`
	// Pre-signed URL to upload the WAPP file.
	UploadUrl string `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	// Expiration time for the upload URL.
	UploadExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=upload_expires_at,json=uploadExpiresAt,proto3" json:"upload_expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitiatePublishResponse) Reset() {
	*x = InitiatePublishResponse{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePublishResponse) ProtoMessage() {}

func (x *InitiatePublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePublishResponse.ProtoReflect.Descriptor instead.
func (*InitiatePublishResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{2}
}

func (x *InitiatePublishResponse) GetPublishId() string {
	if x != nil {
		return x.PublishId
	}
	return ""
}

func (x *InitiatePublishResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *InitiatePublishResponse) GetUploadExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadExpiresAt
	}
	return nil
}

// Request to confirm upload completion.
type ConfirmPublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Publish operation ID.
	PublishId     string `protobuf:"bytes,1,opt,name=publish_id,json=publishId,proto3" json:"publish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPublishRequest) Reset() {
	*x = ConfirmPublishRequest{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPublishRequest) ProtoMessage() {}

func (x *ConfirmPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPublishRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPublishRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmPublishRequest) GetPublishId() string {
	if x != nil {
		return x.PublishId
	}
	return ""
}

// Response to confirm publish.
type ConfirmPublishResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current status of the publish operation.
	Status        PublishStatus `protobuf:"varint,1,opt,name=status,proto3,enum=wippy.hub.module.v1.PublishStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPublishResponse) Reset() {
	*x = ConfirmPublishResponse{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPublishResponse) ProtoMessage() {}

func (x *ConfirmPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPublishResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPublishResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmPublishResponse) GetStatus() PublishStatus {
	if x != nil {
		return x.Status
	}
	return PublishStatus_PUBLISH_STATUS_UNSPECIFIED
}

// Request to get publish status.
type GetPublishStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Publish operation ID.
	PublishId     string `protobuf:"bytes,1,opt,name=publish_id,json=publishId,proto3" json:"publish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishStatusRequest) Reset() {
	*x = GetPublishStatusRequest{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishStatusRequest) ProtoMessage() {}

func (x *GetPublishStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPublishStatusRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetPublishStatusRequest) GetPublishId() string {
	if x != nil {
		return x.PublishId
	}
	return ""
}

// Response with publish status.
type GetPublishStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current status.
	Status PublishStatus `protobuf:"varint,1,opt,name=status,proto3,enum=wippy.hub.module.v1.PublishStatus" json:"status,omitempty"`
	// Detailed status information.
	Details       *PublishStatusDetails `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishStatusResponse) Reset() {
	*x = GetPublishStatusResponse{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishStatusResponse) ProtoMessage() {}

func (x *GetPublishStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPublishStatusResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetPublishStatusResponse) GetStatus() PublishStatus {
	if x != nil {
		return x.Status
	}
	return PublishStatus_PUBLISH_STATUS_UNSPECIFIED
}

func (x *GetPublishStatusResponse) GetDetails() *PublishStatusDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// Detailed status information.
type PublishStatusDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error message if failed.
	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Error code if failed.
	ErrorCode string `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Published version if completed.
	Version *Version `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Processing stage information.
	Stage string `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"`
	// Progress percentage (0-100).
	Progress      int32 `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishStatusDetails) Reset() {
	*x = PublishStatusDetails{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishStatusDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishStatusDetails) ProtoMessage() {}

func (x *PublishStatusDetails) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishStatusDetails.ProtoReflect.Descriptor instead.
func (*PublishStatusDetails) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{7}
}

func (x *PublishStatusDetails) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PublishStatusDetails) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PublishStatusDetails) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *PublishStatusDetails) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *PublishStatusDetails) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

// Request to cancel a publish operation.
type CancelPublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Publish operation ID.
	PublishId     string `protobuf:"bytes,1,opt,name=publish_id,json=publishId,proto3" json:"publish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPublishRequest) Reset() {
	*x = CancelPublishRequest{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPublishRequest) ProtoMessage() {}

func (x *CancelPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPublishRequest.ProtoReflect.Descriptor instead.
func (*CancelPublishRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{8}
}

func (x *CancelPublishRequest) GetPublishId() string {
	if x != nil {
		return x.PublishId
	}
	return ""
}

// Response to cancel publish.
type CancelPublishResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether cancellation was successful.
	Cancelled     bool `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPublishResponse) Reset() {
	*x = CancelPublishResponse{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPublishResponse) ProtoMessage() {}

func (x *CancelPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPublishResponse.ProtoReflect.Descriptor instead.
func (*CancelPublishResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{9}
}

func (x *CancelPublishResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

// Request to yank a version.
type YankVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module reference.
	//
	// Types that are valid to be assigned to Module:
	//
	//	*YankVersionRequest_ModuleId
	//	*YankVersionRequest_ModuleName
	Module isYankVersionRequest_Module `protobuf_oneof:"module"`
	// Version to yank.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Reason for yanking.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YankVersionRequest) Reset() {
	*x = YankVersionRequest{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YankVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YankVersionRequest) ProtoMessage() {}

func (x *YankVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YankVersionRequest.ProtoReflect.Descriptor instead.
func (*YankVersionRequest) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{10}
}

func (x *YankVersionRequest) GetModule() isYankVersionRequest_Module {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *YankVersionRequest) GetModuleId() string {
	if x != nil {
		if x, ok := x.Module.(*YankVersionRequest_ModuleId); ok {
			return x.ModuleId
		}
	}
	return ""
}

func (x *YankVersionRequest) GetModuleName() *ModuleName {
	if x != nil {
		if x, ok := x.Module.(*YankVersionRequest_ModuleName); ok {
			return x.ModuleName
		}
	}
	return nil
}

func (x *YankVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *YankVersionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type isYankVersionRequest_Module interface {
	isYankVersionRequest_Module()
}

type YankVersionRequest_ModuleId struct {
	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3,oneof"`
}

type YankVersionRequest_ModuleName struct {
	ModuleName *ModuleName `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3,oneof"`
}

func (*YankVersionRequest_ModuleId) isYankVersionRequest_Module() {}

func (*YankVersionRequest_ModuleName) isYankVersionRequest_Module() {}

// Response to yank version.
type YankVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The yanked version.
	Version       *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YankVersionResponse) Reset() {
	*x = YankVersionResponse{}
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YankVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YankVersionResponse) ProtoMessage() {}

func (x *YankVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_hub_module_v1_publish_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YankVersionResponse.ProtoReflect.Descriptor instead.
func (*YankVersionResponse) Descriptor() ([]byte, []int) {
	return file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP(), []int{11}
}

func (x *YankVersionResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

var File_wippy_hub_module_v1_publish_service_proto protoreflect.FileDescriptor

const file_wippy_hub_module_v1_publish_service_proto_rawDesc = "" +
	"\n" +
	")wippy/hub/module/v1/publish_service.proto\x12\x13wippy.hub.module.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!wippy/hub/module/v1/version.proto\"\x87\x03\n" +
	"\x16InitiatePublishRequest\x12'\n" +
	"\tmodule_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\bmoduleId\x12B\n" +
	"\vmodule_name\x18\x02 \x01(\v2\x1f.wippy.hub.module.v1.ModuleNameH\x00R\n" +
	"moduleName\x12#\n" +
	"\aversion\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x18@H\x01R\aversion\x122\n" +
	"\x05label\x18\a \x01(\tB\x1a\xbaH\x17r\x15\x18 2\x11^[a-z][a-z0-9-]*$H\x01R\x05label\x12.\n" +
	"\x13expected_size_bytes\x18\x04 \x01(\x04R\x11expectedSizeBytes\x12 \n" +
	"\x06digest\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x98\x01@R\x06digest\x12\x1c\n" +
	"\tprotected\x18\x06 \x01(\bR\tprotected\x12#\n" +
	"\rrelease_notes\x18\b \x01(\tR\freleaseNotesB\b\n" +
	"\x06moduleB\b\n" +
	"\x06target\"H\n" +
	"\n" +
	"ModuleName\x12\x1b\n" +
	"\x03org\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x03org\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x04name\"\x9f\x01\n" +
	"\x17InitiatePublishResponse\x12\x1d\n" +
	"\n" +
	"publish_id\x18\x01 \x01(\tR\tpublishId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12F\n" +
	"\x11upload_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0fuploadExpiresAt\"@\n" +
	"\x15ConfirmPublishRequest\x12'\n" +
	"\n" +
	"publish_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tpublishId\"T\n" +
	"\x16ConfirmPublishResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".wippy.hub.module.v1.PublishStatusR\x06status\"B\n" +
	"\x17GetPublishStatusRequest\x12'\n" +
	"\n" +
	"publish_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tpublishId\"\x9b\x01\n" +
	"\x18GetPublishStatusResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".wippy.hub.module.v1.PublishStatusR\x06status\x12C\n" +
	"\adetails\x18\x02 \x01(\v2).wippy.hub.module.v1.PublishStatusDetailsR\adetails\"\xc4\x01\n" +
	"\x14PublishStatusDetails\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x126\n" +
	"\aversion\x18\x03 \x01(\v2\x1c.wippy.hub.module.v1.VersionR\aversion\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\tR\x05stage\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x05R\bprogress\"?\n" +
	"\x14CancelPublishRequest\x12'\n" +
	"\n" +
	"publish_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tpublishId\"5\n" +
	"\x15CancelPublishResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"\xc8\x01\n" +
	"\x12YankVersionRequest\x12'\n" +
	"\tmodule_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\bmoduleId\x12B\n" +
	"\vmodule_name\x18\x02 \x01(\v2\x1f.wippy.hub.module.v1.ModuleNameH\x00R\n" +
	"moduleName\x12#\n" +
	"\aversion\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\aversion\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reasonB\b\n" +
	"\x06module\"M\n" +
	"\x13YankVersionResponse\x126\n" +
	"\aversion\x18\x01 \x01(\v2\x1c.wippy.hub.module.v1.VersionR\aversion*\xe7\x01\n" +
	"\rPublishStatus\x12\x1e\n" +
	"\x1aPUBLISH_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPUBLISH_STATUS_PENDING_UPLOAD\x10\x01\x12\x1d\n" +
	"\x19PUBLISH_STATUS_PROCESSING\x10\x02\x12\x1d\n" +
	"\x19PUBLISH_STATUS_VALIDATING\x10\x03\x12\x1c\n" +
	"\x18PUBLISH_STATUS_COMPLETED\x10\x04\x12\x19\n" +
	"\x15PUBLISH_STATUS_FAILED\x10\x05\x12\x1c\n" +
	"\x18PUBLISH_STATUS_CANCELLED\x10\x062\xb1\x04\n" +
	"\x0ePublishService\x12n\n" +
	"\x0fInitiatePublish\x12+.wippy.hub.module.v1.InitiatePublishRequest\x1a,.wippy.hub.module.v1.InitiatePublishResponse\"\x00\x12k\n" +
	"\x0eConfirmPublish\x12*.wippy.hub.module.v1.ConfirmPublishRequest\x1a+.wippy.hub.module.v1.ConfirmPublishResponse\"\x00\x12t\n" +
	"\x10GetPublishStatus\x12,.wippy.hub.module.v1.GetPublishStatusRequest\x1a-.wippy.hub.module.v1.GetPublishStatusResponse\"\x03\x90\x02\x01\x12h\n" +
	"\rCancelPublish\x12).wippy.hub.module.v1.CancelPublishRequest\x1a*.wippy.hub.module.v1.CancelPublishResponse\"\x00\x12b\n" +
	"\vYankVersion\x12'.wippy.hub.module.v1.YankVersionRequest\x1a(.wippy.hub.module.v1.YankVersionResponse\"\x00B;Z9github.com/wippyai/proto-api/wippy/hub/module/v1;modulev1b\x06proto3"

var (
	file_wippy_hub_module_v1_publish_service_proto_rawDescOnce sync.Once
	file_wippy_hub_module_v1_publish_service_proto_rawDescData []byte
)

func file_wippy_hub_module_v1_publish_service_proto_rawDescGZIP() []byte {
	file_wippy_hub_module_v1_publish_service_proto_rawDescOnce.Do(func() {
		file_wippy_hub_module_v1_publish_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_hub_module_v1_publish_service_proto_rawDesc), len(file_wippy_hub_module_v1_publish_service_proto_rawDesc)))
	})
	return file_wippy_hub_module_v1_publish_service_proto_rawDescData
}

var file_wippy_hub_module_v1_publish_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wippy_hub_module_v1_publish_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_wippy_hub_module_v1_publish_service_proto_goTypes = []any{
	(PublishStatus)(0),               // 0: wippy.hub.module.v1.PublishStatus
	(*InitiatePublishRequest)(nil),   // 1: wippy.hub.module.v1.InitiatePublishRequest
	(*ModuleName)(nil),               // 2: wippy.hub.module.v1.ModuleName
	(*InitiatePublishResponse)(nil),  // 3: wippy.hub.module.v1.InitiatePublishResponse
	(*ConfirmPublishRequest)(nil),    // 4: wippy.hub.module.v1.ConfirmPublishRequest
	(*ConfirmPublishResponse)(nil),   // 5: wippy.hub.module.v1.ConfirmPublishResponse
	(*GetPublishStatusRequest)(nil),  // 6: wippy.hub.module.v1.GetPublishStatusRequest
	(*GetPublishStatusResponse)(nil), // 7: wippy.hub.module.v1.GetPublishStatusResponse
	(*PublishStatusDetails)(nil),     // 8: wippy.hub.module.v1.PublishStatusDetails
	(*CancelPublishRequest)(nil),     // 9: wippy.hub.module.v1.CancelPublishRequest
	(*CancelPublishResponse)(nil),    // 10: wippy.hub.module.v1.CancelPublishResponse
	(*YankVersionRequest)(nil),       // 11: wippy.hub.module.v1.YankVersionRequest
	(*YankVersionResponse)(nil),      // 12: wippy.hub.module.v1.YankVersionResponse
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
	(*Version)(nil),                  // 14: wippy.hub.module.v1.Version
}
var file_wippy_hub_module_v1_publish_service_proto_depIdxs = []int32{
	2,  // 0: wippy.hub.module.v1.InitiatePublishRequest.module_name:type_name -> wippy.hub.module.v1.ModuleName
	13, // 1: wippy.hub.module.v1.InitiatePublishResponse.upload_expires_at:type_name -> google.protobuf.Timestamp
	0,  // 2: wippy.hub.module.v1.ConfirmPublishResponse.status:type_name -> wippy.hub.module.v1.PublishStatus
	0,  // 3: wippy.hub.module.v1.GetPublishStatusResponse.status:type_name -> wippy.hub.module.v1.PublishStatus
	8,  // 4: wippy.hub.module.v1.GetPublishStatusResponse.details:type_name -> wippy.hub.module.v1.PublishStatusDetails
	14, // 5: wippy.hub.module.v1.PublishStatusDetails.version:type_name -> wippy.hub.module.v1.Version
	2,  // 6: wippy.hub.module.v1.YankVersionRequest.module_name:type_name -> wippy.hub.module.v1.ModuleName
	14, // 7: wippy.hub.module.v1.YankVersionResponse.version:type_name -> wippy.hub.module.v1.Version
	1,  // 8: wippy.hub.module.v1.PublishService.InitiatePublish:input_type -> wippy.hub.module.v1.InitiatePublishRequest
	4,  // 9: wippy.hub.module.v1.PublishService.ConfirmPublish:input_type -> wippy.hub.module.v1.ConfirmPublishRequest
	6,  // 10: wippy.hub.module.v1.PublishService.GetPublishStatus:input_type -> wippy.hub.module.v1.GetPublishStatusRequest
	9,  // 11: wippy.hub.module.v1.PublishService.CancelPublish:input_type -> wippy.hub.module.v1.CancelPublishRequest
	11, // 12: wippy.hub.module.v1.PublishService.YankVersion:input_type -> wippy.hub.module.v1.YankVersionRequest
	3,  // 13: wippy.hub.module.v1.PublishService.InitiatePublish:output_type -> wippy.hub.module.v1.InitiatePublishResponse
	5,  // 14: wippy.hub.module.v1.PublishService.ConfirmPublish:output_type -> wippy.hub.module.v1.ConfirmPublishResponse
	7,  // 15: wippy.hub.module.v1.PublishService.GetPublishStatus:output_type -> wippy.hub.module.v1.GetPublishStatusResponse
	10, // 16: wippy.hub.module.v1.PublishService.CancelPublish:output_type -> wippy.hub.module.v1.CancelPublishResponse
	12, // 17: wippy.hub.module.v1.PublishService.YankVersion:output_type -> wippy.hub.module.v1.YankVersionResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_wippy_hub_module_v1_publish_service_proto_init() }
func file_wippy_hub_module_v1_publish_service_proto_init() {
	if File_wippy_hub_module_v1_publish_service_proto != nil {
		return
	}
	file_wippy_hub_module_v1_version_proto_init()
	file_wippy_hub_module_v1_publish_service_proto_msgTypes[0].OneofWrappers = []any{
		(*InitiatePublishRequest_ModuleId)(nil),
		(*InitiatePublishRequest_ModuleName)(nil),
		(*InitiatePublishRequest_Version)(nil),
		(*InitiatePublishRequest_Label)(nil),
	}
	file_wippy_hub_module_v1_publish_service_proto_msgTypes[10].OneofWrappers = []any{
		(*YankVersionRequest_ModuleId)(nil),
		(*YankVersionRequest_ModuleName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_hub_module_v1_publish_service_proto_rawDesc), len(file_wippy_hub_module_v1_publish_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_hub_module_v1_publish_service_proto_goTypes,
		DependencyIndexes: file_wippy_hub_module_v1_publish_service_proto_depIdxs,
		EnumInfos:         file_wippy_hub_module_v1_publish_service_proto_enumTypes,
		MessageInfos:      file_wippy_hub_module_v1_publish_service_proto_msgTypes,
	}.Build()
	File_wippy_hub_module_v1_publish_service_proto = out.File
	file_wippy_hub_module_v1_publish_service_proto_goTypes = nil
	file_wippy_hub_module_v1_publish_service_proto_depIdxs = nil
}
