// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wippy/registry/module/v1/download_service.proto

package modulev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitIds     []string               `protobuf:"bytes,1,rep,name=commit_ids,json=commitIds,proto3" json:"commit_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_wippy_registry_module_v1_download_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_module_v1_download_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_wippy_registry_module_v1_download_service_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadRequest) GetCommitIds() []string {
	if x != nil {
		return x.CommitIds
	}
	return nil
}

type DownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Contents of the references in the same order as requested.
	Contents      []*DownloadResponse_Content `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_wippy_registry_module_v1_download_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_module_v1_download_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_wippy_registry_module_v1_download_service_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadResponse) GetContents() []*DownloadResponse_Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

// Content for a single Commit.
type DownloadResponse_Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Commit associated with the Content.
	Commit *Commit `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	// The Files of the content.
	Files         []*File `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse_Content) Reset() {
	*x = DownloadResponse_Content{}
	mi := &file_wippy_registry_module_v1_download_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse_Content) ProtoMessage() {}

func (x *DownloadResponse_Content) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_module_v1_download_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse_Content.ProtoReflect.Descriptor instead.
func (*DownloadResponse_Content) Descriptor() ([]byte, []int) {
	return file_wippy_registry_module_v1_download_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DownloadResponse_Content) GetCommit() *Commit {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *DownloadResponse_Content) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_wippy_registry_module_v1_download_service_proto protoreflect.FileDescriptor

const file_wippy_registry_module_v1_download_service_proto_rawDesc = "" +
	"\n" +
	"/wippy/registry/module/v1/download_service.proto\x12\x18wippy.registry.module.v1\x1a\x1bbuf/validate/validate.proto\x1a%wippy/registry/module/v1/commit.proto\x1a#wippy/registry/module/v1/file.proto\"=\n" +
	"\x0fDownloadRequest\x12*\n" +
	"\n" +
	"commit_ids\x18\x01 \x03(\tB\v\xbaH\b\x92\x01\x05\b\x01\x10\x80\x02R\tcommitIds\"\xf0\x01\n" +
	"\x10DownloadResponse\x12X\n" +
	"\bcontents\x18\x01 \x03(\v22.wippy.registry.module.v1.DownloadResponse.ContentB\b\xbaH\x05\x92\x01\x02\b\x01R\bcontents\x1a\x81\x01\n" +
	"\aContent\x12@\n" +
	"\x06commit\x18\x01 \x01(\v2 .wippy.registry.module.v1.CommitB\x06\xbaH\x03\xc8\x01\x01R\x06commit\x124\n" +
	"\x05files\x18\x02 \x03(\v2\x1e.wippy.registry.module.v1.FileR\x05files2y\n" +
	"\x0fDownloadService\x12f\n" +
	"\bDownload\x12).wippy.registry.module.v1.DownloadRequest\x1a*.wippy.registry.module.v1.DownloadResponse\"\x03\x90\x02\x01BIZGgithub.com/wippyai/module-registry-proto-go/registry/module/v1;modulev1b\x06proto3"

var (
	file_wippy_registry_module_v1_download_service_proto_rawDescOnce sync.Once
	file_wippy_registry_module_v1_download_service_proto_rawDescData []byte
)

func file_wippy_registry_module_v1_download_service_proto_rawDescGZIP() []byte {
	file_wippy_registry_module_v1_download_service_proto_rawDescOnce.Do(func() {
		file_wippy_registry_module_v1_download_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_registry_module_v1_download_service_proto_rawDesc), len(file_wippy_registry_module_v1_download_service_proto_rawDesc)))
	})
	return file_wippy_registry_module_v1_download_service_proto_rawDescData
}

var file_wippy_registry_module_v1_download_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wippy_registry_module_v1_download_service_proto_goTypes = []any{
	(*DownloadRequest)(nil),          // 0: wippy.registry.module.v1.DownloadRequest
	(*DownloadResponse)(nil),         // 1: wippy.registry.module.v1.DownloadResponse
	(*DownloadResponse_Content)(nil), // 2: wippy.registry.module.v1.DownloadResponse.Content
	(*Commit)(nil),                   // 3: wippy.registry.module.v1.Commit
	(*File)(nil),                     // 4: wippy.registry.module.v1.File
}
var file_wippy_registry_module_v1_download_service_proto_depIdxs = []int32{
	2, // 0: wippy.registry.module.v1.DownloadResponse.contents:type_name -> wippy.registry.module.v1.DownloadResponse.Content
	3, // 1: wippy.registry.module.v1.DownloadResponse.Content.commit:type_name -> wippy.registry.module.v1.Commit
	4, // 2: wippy.registry.module.v1.DownloadResponse.Content.files:type_name -> wippy.registry.module.v1.File
	0, // 3: wippy.registry.module.v1.DownloadService.Download:input_type -> wippy.registry.module.v1.DownloadRequest
	1, // 4: wippy.registry.module.v1.DownloadService.Download:output_type -> wippy.registry.module.v1.DownloadResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wippy_registry_module_v1_download_service_proto_init() }
func file_wippy_registry_module_v1_download_service_proto_init() {
	if File_wippy_registry_module_v1_download_service_proto != nil {
		return
	}
	file_wippy_registry_module_v1_commit_proto_init()
	file_wippy_registry_module_v1_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_registry_module_v1_download_service_proto_rawDesc), len(file_wippy_registry_module_v1_download_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_registry_module_v1_download_service_proto_goTypes,
		DependencyIndexes: file_wippy_registry_module_v1_download_service_proto_depIdxs,
		MessageInfos:      file_wippy_registry_module_v1_download_service_proto_msgTypes,
	}.Build()
	File_wippy_registry_module_v1_download_service_proto = out.File
	file_wippy_registry_module_v1_download_service_proto_goTypes = nil
	file_wippy_registry_module_v1_download_service_proto_depIdxs = nil
}
