// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wippy/registry/module/v1/file.proto

package modulev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A file that can be read or written to from disk.
// A File includes a path and associated content.
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path of the File.
	//
	// The path must be relative, and cannot contain any "." or ".." components.
	// The separator "/" must be used.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The content of the File.
	Content       []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_wippy_registry_module_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_module_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_wippy_registry_module_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_wippy_registry_module_v1_file_proto protoreflect.FileDescriptor

const file_wippy_registry_module_v1_file_proto_rawDesc = "" +
	"\n" +
	"#wippy/registry/module/v1/file.proto\x12\x18wippy.registry.module.v1\x1a\x1bbuf/validate/validate.proto\"\x97\x01\n" +
	"\x04File\x12i\n" +
	"\x04path\x18\x01 \x01(\tBU\xbaHR\xc8\x01\x01rM\x18\x80 2D^([^/.][^/]?|[^/][^/.]|[^/]{3,})(/([^/.][^/]?|[^/][^/.]|[^/]{3,}))*$\xba\x01\x01\\R\x04path\x12$\n" +
	"\acontent\x18\x02 \x01(\fB\n" +
	"\xbaH\az\x05\x18\x80\xad\xe2\x04R\acontentBIZGgithub.com/wippyai/module-registry-proto-go/registry/module/v1;modulev1b\x06proto3"

var (
	file_wippy_registry_module_v1_file_proto_rawDescOnce sync.Once
	file_wippy_registry_module_v1_file_proto_rawDescData []byte
)

func file_wippy_registry_module_v1_file_proto_rawDescGZIP() []byte {
	file_wippy_registry_module_v1_file_proto_rawDescOnce.Do(func() {
		file_wippy_registry_module_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_registry_module_v1_file_proto_rawDesc), len(file_wippy_registry_module_v1_file_proto_rawDesc)))
	})
	return file_wippy_registry_module_v1_file_proto_rawDescData
}

var file_wippy_registry_module_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wippy_registry_module_v1_file_proto_goTypes = []any{
	(*File)(nil), // 0: wippy.registry.module.v1.File
}
var file_wippy_registry_module_v1_file_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wippy_registry_module_v1_file_proto_init() }
func file_wippy_registry_module_v1_file_proto_init() {
	if File_wippy_registry_module_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_registry_module_v1_file_proto_rawDesc), len(file_wippy_registry_module_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wippy_registry_module_v1_file_proto_goTypes,
		DependencyIndexes: file_wippy_registry_module_v1_file_proto_depIdxs,
		MessageInfos:      file_wippy_registry_module_v1_file_proto_msgTypes,
	}.Build()
	File_wippy_registry_module_v1_file_proto = out.File
	file_wippy_registry_module_v1_file_proto_goTypes = nil
	file_wippy_registry_module_v1_file_proto_depIdxs = nil
}
