// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wippy/registry/module/v1/label_service.proto

package modulev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	CommitId      string                 `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLabelRequest) Reset() {
	*x = CreateLabelRequest{}
	mi := &file_wippy_registry_module_v1_label_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLabelRequest) ProtoMessage() {}

func (x *CreateLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_module_v1_label_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLabelRequest.ProtoReflect.Descriptor instead.
func (*CreateLabelRequest) Descriptor() ([]byte, []int) {
	return file_wippy_registry_module_v1_label_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLabelRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *CreateLabelRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *CreateLabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateLabelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         *Label                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLabelResponse) Reset() {
	*x = CreateLabelResponse{}
	mi := &file_wippy_registry_module_v1_label_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLabelResponse) ProtoMessage() {}

func (x *CreateLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_module_v1_label_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLabelResponse.ProtoReflect.Descriptor instead.
func (*CreateLabelResponse) Descriptor() ([]byte, []int) {
	return file_wippy_registry_module_v1_label_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLabelResponse) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

type ListModuleLabelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by module IDs
	ModuleIds     []string `protobuf:"bytes,1,rep,name=module_ids,json=moduleIds,proto3" json:"module_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModuleLabelsRequest) Reset() {
	*x = ListModuleLabelsRequest{}
	mi := &file_wippy_registry_module_v1_label_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModuleLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModuleLabelsRequest) ProtoMessage() {}

func (x *ListModuleLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_module_v1_label_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModuleLabelsRequest.ProtoReflect.Descriptor instead.
func (*ListModuleLabelsRequest) Descriptor() ([]byte, []int) {
	return file_wippy_registry_module_v1_label_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListModuleLabelsRequest) GetModuleIds() []string {
	if x != nil {
		return x.ModuleIds
	}
	return nil
}

type ListModuleLabelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The labels matching the request criteria
	Labels        []*Label `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModuleLabelsResponse) Reset() {
	*x = ListModuleLabelsResponse{}
	mi := &file_wippy_registry_module_v1_label_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModuleLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModuleLabelsResponse) ProtoMessage() {}

func (x *ListModuleLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_module_v1_label_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModuleLabelsResponse.ProtoReflect.Descriptor instead.
func (*ListModuleLabelsResponse) Descriptor() ([]byte, []int) {
	return file_wippy_registry_module_v1_label_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListModuleLabelsResponse) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_wippy_registry_module_v1_label_service_proto protoreflect.FileDescriptor

const file_wippy_registry_module_v1_label_service_proto_rawDesc = "" +
	"\n" +
	",wippy/registry/module/v1/label_service.proto\x12\x18wippy.registry.module.v1\x1a\x1bbuf/validate/validate.proto\x1a$wippy/registry/module/v1/label.proto\"\xc6\x02\n" +
	"\x12CreateLabelRequest\x12(\n" +
	"\tmodule_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bmoduleId\x12(\n" +
	"\tcommit_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bcommitId\x12\xdb\x01\n" +
	"\x04name\x18\x03 \x01(\tB\xc6\x01\xbaH\xc2\x01\xc8\x01\x01r\xbc\x01\x10\x03\x18<2\xb5\x01^v?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$R\x04name\"L\n" +
	"\x13CreateLabelResponse\x125\n" +
	"\x05label\x18\x01 \x01(\v2\x1f.wippy.registry.module.v1.LabelR\x05label\"N\n" +
	"\x17ListModuleLabelsRequest\x123\n" +
	"\n" +
	"module_ids\x18\x01 \x03(\tB\x14\xbaH\x11\x92\x01\x0e\b\x01\x10\x80\x02\x18\x01\"\x05r\x03\xb0\x01\x01R\tmoduleIds\"S\n" +
	"\x18ListModuleLabelsResponse\x127\n" +
	"\x06labels\x18\x01 \x03(\v2\x1f.wippy.registry.module.v1.LabelR\x06labels2\xff\x01\n" +
	"\fLabelService\x12o\n" +
	"\vCreateLabel\x12,.wippy.registry.module.v1.CreateLabelRequest\x1a-.wippy.registry.module.v1.CreateLabelResponse\"\x03\x90\x02\x02\x12~\n" +
	"\x10ListModuleLabels\x121.wippy.registry.module.v1.ListModuleLabelsRequest\x1a2.wippy.registry.module.v1.ListModuleLabelsResponse\"\x03\x90\x02\x01BIZGgithub.com/wippyai/module-registry-proto-go/registry/module/v1;modulev1b\x06proto3"

var (
	file_wippy_registry_module_v1_label_service_proto_rawDescOnce sync.Once
	file_wippy_registry_module_v1_label_service_proto_rawDescData []byte
)

func file_wippy_registry_module_v1_label_service_proto_rawDescGZIP() []byte {
	file_wippy_registry_module_v1_label_service_proto_rawDescOnce.Do(func() {
		file_wippy_registry_module_v1_label_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_registry_module_v1_label_service_proto_rawDesc), len(file_wippy_registry_module_v1_label_service_proto_rawDesc)))
	})
	return file_wippy_registry_module_v1_label_service_proto_rawDescData
}

var file_wippy_registry_module_v1_label_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wippy_registry_module_v1_label_service_proto_goTypes = []any{
	(*CreateLabelRequest)(nil),       // 0: wippy.registry.module.v1.CreateLabelRequest
	(*CreateLabelResponse)(nil),      // 1: wippy.registry.module.v1.CreateLabelResponse
	(*ListModuleLabelsRequest)(nil),  // 2: wippy.registry.module.v1.ListModuleLabelsRequest
	(*ListModuleLabelsResponse)(nil), // 3: wippy.registry.module.v1.ListModuleLabelsResponse
	(*Label)(nil),                    // 4: wippy.registry.module.v1.Label
}
var file_wippy_registry_module_v1_label_service_proto_depIdxs = []int32{
	4, // 0: wippy.registry.module.v1.CreateLabelResponse.label:type_name -> wippy.registry.module.v1.Label
	4, // 1: wippy.registry.module.v1.ListModuleLabelsResponse.labels:type_name -> wippy.registry.module.v1.Label
	0, // 2: wippy.registry.module.v1.LabelService.CreateLabel:input_type -> wippy.registry.module.v1.CreateLabelRequest
	2, // 3: wippy.registry.module.v1.LabelService.ListModuleLabels:input_type -> wippy.registry.module.v1.ListModuleLabelsRequest
	1, // 4: wippy.registry.module.v1.LabelService.CreateLabel:output_type -> wippy.registry.module.v1.CreateLabelResponse
	3, // 5: wippy.registry.module.v1.LabelService.ListModuleLabels:output_type -> wippy.registry.module.v1.ListModuleLabelsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wippy_registry_module_v1_label_service_proto_init() }
func file_wippy_registry_module_v1_label_service_proto_init() {
	if File_wippy_registry_module_v1_label_service_proto != nil {
		return
	}
	file_wippy_registry_module_v1_label_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_registry_module_v1_label_service_proto_rawDesc), len(file_wippy_registry_module_v1_label_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wippy_registry_module_v1_label_service_proto_goTypes,
		DependencyIndexes: file_wippy_registry_module_v1_label_service_proto_depIdxs,
		MessageInfos:      file_wippy_registry_module_v1_label_service_proto_msgTypes,
	}.Build()
	File_wippy_registry_module_v1_label_service_proto = out.File
	file_wippy_registry_module_v1_label_service_proto_goTypes = nil
	file_wippy_registry_module_v1_label_service_proto_depIdxs = nil
}
