// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wippy/registry/module/v1/module.proto

package modulev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reference to a Module by either ID or name within an organization.
type ModuleRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ModuleRef_Id
	//	*ModuleRef_NameRef
	Value         isModuleRef_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleRef) Reset() {
	*x = ModuleRef{}
	mi := &file_wippy_registry_module_v1_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleRef) ProtoMessage() {}

func (x *ModuleRef) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_module_v1_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleRef.ProtoReflect.Descriptor instead.
func (*ModuleRef) Descriptor() ([]byte, []int) {
	return file_wippy_registry_module_v1_module_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleRef) GetValue() isModuleRef_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ModuleRef) GetId() string {
	if x != nil {
		if x, ok := x.Value.(*ModuleRef_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *ModuleRef) GetNameRef() *ModuleRef_ModuleNameRef {
	if x != nil {
		if x, ok := x.Value.(*ModuleRef_NameRef); ok {
			return x.NameRef
		}
	}
	return nil
}

type isModuleRef_Value interface {
	isModuleRef_Value()
}

type ModuleRef_Id struct {
	// The ID of the Module.
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type ModuleRef_NameRef struct {
	// Reference by module name and organization ID.
	NameRef *ModuleRef_ModuleNameRef `protobuf:"bytes,2,opt,name=name_ref,json=nameRef,proto3,oneof"`
}

func (*ModuleRef_Id) isModuleRef_Value() {}

func (*ModuleRef_NameRef) isModuleRef_Value() {}

// A module within the registry.
type Module struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName string                 `protobuf:"bytes,4,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	CreateTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_wippy_registry_module_v1_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_module_v1_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_wippy_registry_module_v1_module_proto_rawDescGZIP(), []int{1}
}

func (x *Module) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Module) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Module) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Module) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *Module) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Module) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// Reference to a Module by name and organization ID.
type ModuleRef_ModuleNameRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Organization ID that the module belongs to.
	OrganizationId string `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// The name of the Module.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleRef_ModuleNameRef) Reset() {
	*x = ModuleRef_ModuleNameRef{}
	mi := &file_wippy_registry_module_v1_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleRef_ModuleNameRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleRef_ModuleNameRef) ProtoMessage() {}

func (x *ModuleRef_ModuleNameRef) ProtoReflect() protoreflect.Message {
	mi := &file_wippy_registry_module_v1_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleRef_ModuleNameRef.ProtoReflect.Descriptor instead.
func (*ModuleRef_ModuleNameRef) Descriptor() ([]byte, []int) {
	return file_wippy_registry_module_v1_module_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ModuleRef_ModuleNameRef) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ModuleRef_ModuleNameRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_wippy_registry_module_v1_module_proto protoreflect.FileDescriptor

const file_wippy_registry_module_v1_module_proto_rawDesc = "" +
	"\n" +
	"%wippy/registry/module/v1/module.proto\x12\x18wippy.registry.module.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x01\n" +
	"\tModuleRef\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\x02id\x12N\n" +
	"\bname_ref\x18\x02 \x01(\v21.wippy.registry.module.v1.ModuleRef.ModuleNameRefH\x00R\anameRef\x1a_\n" +
	"\rModuleNameRef\x121\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eorganizationId\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@R\x04nameB\a\n" +
	"\x05value\"\xa2\x02\n" +
	"\x06Module\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@R\x04name\x121\n" +
	"\x0forganization_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eorganizationId\x124\n" +
	"\x11organization_name\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x18 R\x10organizationName\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTimeBIZGgithub.com/wippyai/module-registry-proto-go/registry/module/v1;modulev1b\x06proto3"

var (
	file_wippy_registry_module_v1_module_proto_rawDescOnce sync.Once
	file_wippy_registry_module_v1_module_proto_rawDescData []byte
)

func file_wippy_registry_module_v1_module_proto_rawDescGZIP() []byte {
	file_wippy_registry_module_v1_module_proto_rawDescOnce.Do(func() {
		file_wippy_registry_module_v1_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wippy_registry_module_v1_module_proto_rawDesc), len(file_wippy_registry_module_v1_module_proto_rawDesc)))
	})
	return file_wippy_registry_module_v1_module_proto_rawDescData
}

var file_wippy_registry_module_v1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wippy_registry_module_v1_module_proto_goTypes = []any{
	(*ModuleRef)(nil),               // 0: wippy.registry.module.v1.ModuleRef
	(*Module)(nil),                  // 1: wippy.registry.module.v1.Module
	(*ModuleRef_ModuleNameRef)(nil), // 2: wippy.registry.module.v1.ModuleRef.ModuleNameRef
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_wippy_registry_module_v1_module_proto_depIdxs = []int32{
	2, // 0: wippy.registry.module.v1.ModuleRef.name_ref:type_name -> wippy.registry.module.v1.ModuleRef.ModuleNameRef
	3, // 1: wippy.registry.module.v1.Module.create_time:type_name -> google.protobuf.Timestamp
	3, // 2: wippy.registry.module.v1.Module.update_time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wippy_registry_module_v1_module_proto_init() }
func file_wippy_registry_module_v1_module_proto_init() {
	if File_wippy_registry_module_v1_module_proto != nil {
		return
	}
	file_wippy_registry_module_v1_module_proto_msgTypes[0].OneofWrappers = []any{
		(*ModuleRef_Id)(nil),
		(*ModuleRef_NameRef)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wippy_registry_module_v1_module_proto_rawDesc), len(file_wippy_registry_module_v1_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wippy_registry_module_v1_module_proto_goTypes,
		DependencyIndexes: file_wippy_registry_module_v1_module_proto_depIdxs,
		MessageInfos:      file_wippy_registry_module_v1_module_proto_msgTypes,
	}.Build()
	File_wippy_registry_module_v1_module_proto = out.File
	file_wippy_registry_module_v1_module_proto_goTypes = nil
	file_wippy_registry_module_v1_module_proto_depIdxs = nil
}
